import "./ditto.css";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import ListRow3 from "./components/list-row3";
import ListRow4 from "./components/list-row4";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { id: "menu-item-5796", href: "/", label: "Home" },
    { id: "menu-item-6208", href: "/our-services", label: "Our Services" },
    { id: "menu-item-5793", href: "/about-us", label: "About Us" },
    { id: "menu-item-5908", href: "/blog", label: "Blog" },
    { id: "menu-item-5795", href: "/contact-us", ariacurrent: "page", label: "Contact Us" }
];
const ListRow2_data = [
    { href: "/", label: "Home" },
    { href: "/our-services", label: "Our Services" },
    { href: "/about-us", label: "About Us" },
    { href: "/blog", label: "Blog" },
    { href: "/contact-us", ariacurrent: "page", label: "Contact Us" }
];
const ListRow3_data = [
    { href: "https://www.hammerandanvil.co.za/category/energy/", label: "Energy" },
    { href: "https://www.hammerandanvil.co.za/category/renewable-energy/", label: "Renewable Energy" },
    { href: "https://www.hammerandanvil.co.za/category/uncategorized/", label: "Uncategorized" }
];
const ListRow4_data = [
    { href: "/2025/08/11/from-chaos-to-control-building-a-tailored-energy-management-system-for-better-business-outcomes/", label: "From Chaos to Control: Building a Tailored Energy Management System for Better Business Outcomes" },
    { href: "/2025/08/05/unpacking-the-energy-roadmap-a-strategic-asset-for-your-business-in-south-africa/", label: "Unpacking the Energy Roadmap: A Strategic Asset for Your Business in South Africa" },
    { href: "/2025/07/28/building-a-bankable-business-case-for-solar-guide-for-commercial-industrial-business-decision-makers-in-south-africa/", label: "Building a Bankable Business Case for Solar: Guide for Commercial & Industrial business decision makers in South Africa" },
    { href: "/2025/07/22/tariff-optimisation-strategies-for-reducing-electricity-costs-in-the-ci-sector/", label: "Tariff Optimisation: Strategies for Reducing Electricity Costs in the C&I Sector" }
];
const ListRow_cids: string[][] = [
    ["n22", "n23", "n24"],
    ["n25", "n26", "n27"],
    ["n28", "n29", "n30"],
    ["n31", "n32", "n33"],
    ["n34", "n35", "n36"]
];
const ListRow2_cids: string[][] = [
    ["n426", "n427"],
    ["n428", "n429"],
    ["n430", "n431"],
    ["n432", "n433"],
    ["n434", "n435"]
];
const ListRow3_cids: string[][] = [
    ["n440", "n441"],
    ["n442", "n443"],
    ["n444", "n445"]
];
const ListRow4_cids: string[][] = [
    ["n450", "n451"],
    ["n452", "n453"],
    ["n454", "n455"],
    ["n456", "n457"]
];
const ListRow_styles = [
    { className: "after:w-9.5 after:transform-[matrix(0,0,0,1,0,0)]" },
    { className: "after:w-[4.9375rem] after:transform-[matrix(0,0,0,1,0,0)]" },
    { className: "after:w-14.5 after:transform-[matrix(0,0,0,1,0,0)]" },
    { className: "after:w-7 after:transform-[matrix(0,0,0,1,0,0)]" },
    { className: "after:w-[4.3125rem] after:" }
];
const ListRow2_styles = [
    { className: "pb-1" },
    { className: "py-1" },
    { className: "py-1" },
    { className: "py-1" },
    { className: "py-1" }
];
const ListRow3_styles = [
    { className: "pb-1" },
    { className: "py-1" },
    { className: "py-1" }
];
const ListRow4_styles = [
    { className: "pb-1" },
    { className: "py-1" },
    { className: "py-1" },
    { className: "py-1" }
];

export default function Page() {
  return (
    <>
      <a className="w-px h-px block absolute top-0 left-0 min-w-0 -m-px overflow-hidden text-primary [clip-path:inset(50%)] cursor-pointer" data-cid="n1" href="#ajax-content-wrap">
        Skip to main content
      </a>
      <div className="h-full flex relative z-10 flex-col grow bg-background" data-cid="n2">
        <div className="h-full flex flex-col grow" data-cid="n3">
          {" "}
          <div className="h-33 block bg-background max-lg:h-23.5" data-cid="n4" id="header-space" />
          {" "}
          <div className="h-33 block fixed inset-x-0 z-9998 min-w-0 bg-surface-4 max-lg:h-23.5 max-lg:py-3" data-cid="n5" id="header-outer">
            {" "}
            <header className="h-full block relative z-9998" data-cid="n6" id="top">
              <div className="h-full block relative max-w-375 px-22.5 max-lg:max-w-[88%] max-md:mx-[22.5px] max-lg:px-0 md:max-lg:mx-[2.875rem] 2xl:mx-52.5 before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-8 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-8" data-cid="n7">
                <div className="h-full flex relative max-lg:block before:content-['_'] before:table before:w-0 before:h-33 before:text-foreground before:text-base before:leading-8 max-lg:before:h-0 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-8" data-cid="n8">
                  <div className="w-25 flex relative z-10 max-md:w-82.5 max-lg:block max-lg:float-left max-lg:leading-0 max-lg:text-left md:max-lg:w-[42.2375rem] after:content-[''] after:block after:w-0 after:h-0 max-md:after:w-82.5 md:max-lg:after:w-[42.2375rem]" data-cid="n9">
                    <a className="block relative my-4 self-center text-primary [font-family:'Open_Sans'] text-[1.375rem] font-semibold leading-5.5 tracking-[-1px] cursor-pointer max-lg:inline-block max-lg:align-middle max-lg:static max-lg:right-auto max-lg:bottom-auto max-lg:my-0" data-cid="n10" data-component="link" href="/" id="logo">
                      {" "}
                      <img className="w-25 h-25 block overflow-clip aspect-[auto_300/300] indent-[-9999px] max-lg:w-17.5 max-lg:h-17.5 max-lg:relative" data-cid="n11" data-component="image" alt={"Hammer & Anvil Ventures"} height="300" src="/assets/cloned/images/25371d8dd0a7.png" width="300" />
                      {" "}
                    </a>
                    {" "}
                  </div>
                  {" "}
                  <div className="w-250 h-33 flex left-0 z-1 grow text-center max-lg:w-8 max-lg:h-17.5 max-lg:absolute max-lg:top-0 max-md:left-74.5 max-lg:z-10000 max-lg:items-center max-lg:leading-0 max-lg:text-right md:max-lg:left-[40.2375rem] 2xl:w-305 after:content-[''] after:block after:w-0 after:h-0" data-cid="n12">
                    {" "}
                    <div className="h-full hidden z-10000 min-w-0 max-lg:block max-lg:relative max-lg:pl-2.5 max-lg:align-middle" data-cid="n13">
                      <div className="block transform-[none] max-lg:relative max-lg:top-[2.1875rem] max-lg:-bottom-[2.1875rem] max-lg:text-[1.125rem] max-lg:transform-[matrix(1,0,0,1,0,-10)]" data-cid="n14">
                        <a className="inline text-primary cursor-pointer" data-cid="n15" aria-expanded="false" aria-label="Navigation Menu" href="#slide-out-widget-area" role="button">
                          {" "}
                          <span className="w-5.5 h-px block absolute -m-px overflow-hidden [clip-path:inset(50%)]" data-cid="n16">
                            Menu
                          </span>
                          <span className="w-5.5 h-5 block relative overflow-hidden" data-cid="n17" aria-hidden="true">
                            {" "}
                            <i className="block relative top-[0.5625rem] text-primary text-[0rem] italic leading-0 max-lg:w-5.5 max-lg:-bottom-[0.5625rem] max-lg:leading-[inherit] after:content-[''] after:block after:absolute after:top-0 after:left-0 after:w-5.5 after:h-0.5 after:bg-primary max-lg:after:right-0 max-lg:after:bottom-0 max-lg:after: max-lg:after:origin-[11px_1px]" data-cid="n18">
                              {" "}
                              <i className="w-[1.4rem] h-0.5 block relative text-base leading-5.5 max-lg:w-5.5 before:content-[''] before:block before:absolute before:top-[0.4375rem] before:left-0 before:w-4 before:h-0.5 before:bg-primary max-lg:before:top-1.5 max-lg:before:right-1.5 max-lg:before:-bottom-1.5 after:content-[''] after:block after:absolute after:-top-[0.4375rem] after:left-0 after:w-5.5 after:h-0.5 after:bg-primary max-lg:after:-top-1.5 max-lg:after:right-0 max-lg:after:bottom-1.5" data-cid="n19" />
                              {" "}
                            </i>
                            {" "}
                          </span>
                          {" "}
                        </a>
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <nav className="flex grow max-lg:hidden" data-cid="n20" data-component="nav" aria-label="Main Menu">
                      <ul className="w-full h-33 min-h-px flex z-1 justify-center align-middle leading-px [list-style-type:none] list-outside" data-cid="n21">
                        {ListRow_data.map((d, i) => <ListRow key={i} d={d} cids={ListRow_cids[i]} styles={ListRow_styles[i]} />)}
                      </ul>
                      {" "}
                      <ul className="w-6 h-33 min-h-px flex absolute right-0 z-10 min-w-0 ml-7.5 align-middle leading-px [list-style-type:none] list-outside" data-cid="n37">
                        <li className="flex relative z-100 items-center text-xs leading-3" data-cid="n38">
                          <div className="block z-10" data-cid="n39">
                            <a className="box-content w-6 h-[1.3125rem] block relative z-10 text-muted leading-[1.3125rem] [background-position:100%_0%] bg-no-repeat cursor-pointer" data-cid="n40" data-component="button" aria-expanded="false" aria-label="Navigation Menu" href="#slide-out-widget-area" role="button">
                              {" "}
                              <span className="w-5.5 h-px block absolute z-10 -m-px overflow-hidden [clip-path:inset(50%)]" data-cid="n41">
                                Menu
                                <i className="w-5.5 block relative top-[0.5625rem] right-7.5 -bottom-[0.5625rem] -left-7.5 z-10 -mt-0.5 text-[0rem] italic leading-0 after:content-[''] after:block after:absolute after:inset-y-0 after:-right-[0.025rem] after:left-0 after:w-[1.4rem] after:h-0.5 after:bg-primary after: after:origin-[11.1953px_1px] max-lg:after:w-[1.4rem] max-lg:after:right-auto max-lg:after:bottom-auto max-lg:after:transform-[none] max-lg:after:origin-[initial]" data-cid="n42">
                                  {" "}
                                  <i className="w-[1.4rem] h-0.5 block relative z-10 text-base leading-5.5 before:content-[''] before:block before:absolute before:top-[0.4375rem] before:right-[0.4rem] before:-bottom-[0.4375rem] before:left-0 before:w-4 before:h-0.5 before:bg-primary max-lg:before:w-5.5 max-lg:before:right-auto max-lg:before:bottom-auto after:content-[''] after:block after:absolute after:-top-[0.4375rem] after:bottom-[0.4375rem] after:inset-x-0 after:w-[1.4rem] after:h-0.5 after:bg-primary max-lg:after:w-5.5 max-lg:after:right-auto max-lg:after:bottom-auto" data-cid="n43" />
                                  {" "}
                                </i>
                              </span>
                              <span className="w-5.5 h-[1.3125rem] block relative z-10 overflow-hidden" data-cid="n44" aria-hidden="true">
                                {" "}
                                <i className="w-5.5 block relative top-[0.5625rem] -bottom-[0.5625rem] z-10 text-[0rem] italic leading-0 after:content-[''] after:block after:absolute after:inset-y-0 after:-right-[0.025rem] after:left-0 after:w-[1.4rem] after:h-0.5 after:bg-primary after: after:origin-[11.1953px_1px] max-lg:after:w-[1.4rem] max-lg:after:right-auto max-lg:after:bottom-auto max-lg:after:transform-[none] max-lg:after:origin-[initial]" data-cid="n45">
                                  {" "}
                                  <i className="w-[1.4rem] h-0.5 block relative z-10 text-base leading-5.5 before:content-[''] before:block before:absolute before:top-[0.4375rem] before:right-[0.4rem] before:-bottom-[0.4375rem] before:left-0 before:w-4 before:h-0.5 before:bg-primary max-lg:before:w-5.5 max-lg:before:right-auto max-lg:before:bottom-auto after:content-[''] after:block after:absolute after:-top-[0.4375rem] after:bottom-[0.4375rem] after:inset-x-0 after:w-[1.4rem] after:h-0.5 after:bg-primary max-lg:after:w-5.5 max-lg:after:right-auto max-lg:after:bottom-auto" data-cid="n46" />
                                  {" "}
                                </i>
                                {" "}
                                <i className="w-5.5 block relative top-[0.5625rem] right-7.5 -bottom-[0.5625rem] -left-7.5 z-10 -mt-0.5 text-[0rem] italic leading-0 after:content-[''] after:block after:absolute after:inset-y-0 after:-right-[0.025rem] after:left-0 after:w-[1.4rem] after:h-0.5 after:bg-primary after: after:origin-[11.1953px_1px] max-lg:after:w-[1.4rem] max-lg:after:right-auto max-lg:after:bottom-auto max-lg:after:transform-[none] max-lg:after:origin-[initial]" data-cid="n47">
                                  {" "}
                                  <i className="w-[1.4rem] h-0.5 block relative z-10 text-base leading-5.5 before:content-[''] before:block before:absolute before:top-[0.4375rem] before:right-[0.4rem] before:-bottom-[0.4375rem] before:left-0 before:w-4 before:h-0.5 before:bg-primary max-lg:before:w-5.5 max-lg:before:right-auto max-lg:before:bottom-auto after:content-[''] after:block after:absolute after:-top-[0.4375rem] after:bottom-[0.4375rem] after:inset-x-0 after:w-[1.4rem] after:h-0.5 after:bg-primary max-lg:after:w-5.5 max-lg:after:right-auto max-lg:after:bottom-auto" data-cid="n48" />
                                  {" "}
                                </i>
                              </span>
                              {" "}
                            </a>
                            {" "}
                          </div>
                        </li>
                      </ul>
                      {" "}
                    </nav>
                    {" "}
                    <div className="h-25 block relative -z-100 invisible my-4 leading-0 pointer-events-none max-lg:hidden" data-cid="n49">
                      <img className="w-25 h-25 inline max-w-full overflow-clip aspect-[auto_300/300] pointer-events-none max-lg:hidden" data-cid="n50" alt={"Hammer & Anvil Ventures"} height="300" src="/assets/cloned/images/25371d8dd0a7.png" width="300" />
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </header>
            {" "}
          </div>
          {" "}
          <div className="h-[245.6875rem] flex flex-col grow max-md:h-[279.4375rem] md:max-lg:h-[272.3125rem] 2xl:h-[250.4625rem] after:content-[''] after:block after:fixed after:inset-0 after:z-1000 after:w-320 after:h-200 after:bg-clr-0 after:opacity-0 after: after:origin-[640px_400px] max-md:after:w-[23.4375rem] max-md:after:h-203 max-md:after:origin-[187.5px_406px] md:max-lg:after:w-192 md:max-lg:after:h-256 md:max-lg:after:origin-[384px_512px] 2xl:after:w-480 2xl:after:h-270 2xl:after:origin-[960px_540px]" data-cid="n51" id="ajax-content-wrap">
            <div className="h-[201.3125rem] block relative z-10 grow bg-background max-md:h-[210.6625rem] max-lg:z-11 md:max-lg:h-[214.6875rem] 2xl:h-[210.0875rem] 2xl:min-h-75.5" data-cid="n52">
              <div className="h-full block relative max-w-375 px-22.5 max-lg:max-w-[88%] max-md:mx-[22.5px] max-lg:px-0 md:max-lg:mx-[2.875rem] 2xl:mx-52.5 before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-8 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-8" data-cid="n53" role="main">
                <div className="h-full block relative before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-8 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-8" data-cid="n54">
                  <div className="w-screen block relative left-1/2 -translate-x-1/2 py-[6.4rem] max-md:py-7.5 md:max-lg:py-[3.8375rem] 2xl:py-[9.6rem] before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n55" id="fws_6a844afd42a85">
                    <div className="h-full block absolute top-0 right-0 left-160 -ml-160 overflow-hidden max-md:left-[187.5px] max-md:ml-[-187.5px] md:max-lg:left-96 md:max-lg:-ml-96 2xl:left-240 2xl:-ml-240" data-cid="n56">
                      <div className="h-full block absolute top-0 inset-x-0 z-1 overflow-hidden" data-cid="n57">
                        <div className="h-full block absolute top-0 inset-x-0 bg-cover" data-cid="n58" />
                      </div>
                    </div>
                    <div className="flex relative z-10 flex-wrap after:content-[''] after:block after:w-0 after:h-0" data-cid="n59">
                      <div className="w-160 flex relative items-stretch bg-cover [background-position:50%_50%] max-md:w-[23.4375rem] max-lg:flex-wrap md:max-lg:w-192 2xl:w-240 after:content-[''] after:block after:w-0 after:h-0" data-cid="n60">
                        <div className="flex relative px-[9.6rem] flex-col grow max-md:px-[2.8125rem] md:max-lg:px-[5.7625rem] 2xl:px-[14.4rem]" data-cid="n61">
                          <div className="h-[540.5px] min-h-px block max-md:h-[35.3125rem] md:max-lg:h-[31.55rem] 2xl:h-[32.9375rem]" data-cid="n62">
                            <div className="block mb-6" data-cid="n63">
                              <div className="block" data-cid="n64">
                                <h1 className="block mb-[0.4375rem] [font-family:'Cantata_One'] text-[2.8125rem] leading-[3.5rem] capitalize max-md:text-[2.4375rem] max-md:leading-[3rem] md:max-lg:text-[2.625rem] md:max-lg:leading-[3.25rem] 2xl:text-6xl 2xl:leading-18.5" data-cid="n65" data-component="heading">
                                  Reach out
                                </h1>
                                {" "}
                                <p className="block" data-cid="n66">
                                  Transform your challenges into opportunities. Together, let’s shape a brighter, more prosperous future for your business.
                                </p>
                                {" "}
                              </div>
                              {" "}
                            </div>
                            {" "}
                            <div className="block mb-6" data-cid="n67">
                              <div className="block" data-cid="n68">
                                <h5 className="block mb-[0.4375rem] [font-family:'Cantata_One'] text-xl leading-7" data-cid="n69" data-component="heading">
                                  Contacts
                                </h5>
                                {" "}
                                <p className="h-22 block pb-6" data-cid="n70">
                                  {"E. "}
                                  <a className="inline text-primary cursor-pointer" data-cid="n71" data-component="link" href="mailto:sales@hammerandanvil.co.za">
                                    sales@hammerandanvil.co.za
                                  </a>
                                  <br className="inline" data-cid="n72" />
                                  {" T. "}
                                  <a className="inline text-primary cursor-pointer" data-cid="n73" data-component="link" href="tel:0714424852">
                                    +27 (0) 71 442 4852
                                  </a>
                                </p>
                                {" "}
                                <h5 className="block mb-[0.4375rem] [font-family:'Cantata_One'] text-xl leading-7" data-cid="n74" data-component="heading">
                                  Address
                                </h5>
                                {" "}
                                <p className="h-32 block" data-cid="n75">
                                  32 Umgazi Street
                                  <br className="inline" data-cid="n76" />
                                  {" Ashlea Gardens"}
                                  <br className="inline" data-cid="n77" />
                                  {" Pretoria"}
                                  <br className="inline" data-cid="n78" />
                                  {" 0081"}
                                </p>
                                {" "}
                              </div>
                              {" "}
                            </div>
                            {" "}
                            <div className="block" data-cid="n79">
                              <div className="h-6 block" data-cid="n80" />
                            </div>
                            <div className="block relative before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n81" id="fws_6a844afd434ad">
                              <div className="h-full block absolute top-0 inset-x-0 overflow-hidden" data-cid="n82">
                                <div className="h-full block absolute top-0 inset-x-0 bg-cover" data-cid="n83" />
                                {" "}
                              </div>
                              <div className="h-6 flex relative z-10 flex-wrap after:content-[''] after:block after:w-0 after:h-0" data-cid="n84">
                                <div className="w-full h-6 block relative bg-cover [background-position:50%_50%] after:content-[''] after:block after:w-full after:h-0" data-cid="n85">
                                  <div className="block relative" data-cid="n86">
                                    <div className="block" data-cid="n87">
                                      <div className="block text-left" data-cid="n88">
                                        <h6 className="block [font-family:'Cantata_One'] leading-6" data-cid="n89" data-component="heading">
                                          <span className="inline relative rounded-[200px]" data-cid="n90">
                                            <a className="inline-block relative cursor-pointer whitespace-nowrap after:content-[''] after:block after:absolute after:top-5 after:bottom-0 after:inset-x-0 after:z-1 after:w-[12.9375rem] after:h-0.5 after:opacity-80" data-cid="n91" data-component="button" href="#contact" role="button">
                                              Send Us a Message Below
                                            </a>
                                          </span>
                                        </h6>
                                      </div>
                                      {" "}
                                    </div>
                                    {" "}
                                  </div>
                                  {" "}
                                </div>
                                {" "}
                              </div>
                            </div>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                      <div className="w-160 flex relative rounded-[20px] items-stretch bg-cover [background-position:50%_50%] max-md:w-[23.4375rem] max-lg:flex-wrap md:max-lg:w-192 2xl:w-240 after:content-[''] after:block after:w-0 after:h-0" data-cid="n92">
                        <div className="flex relative px-[1.6rem] rounded-[20px] flex-col grow max-md:px-[11.3px] md:max-lg:px-[1.4375rem] 2xl:px-[2.4rem]" data-cid="n93">
                          <div className="h-[24.875rem] min-h-px block max-md:h-[15.5rem] md:max-lg:h-[482.7px] 2xl:h-[585.1px]" data-cid="n94">
                            <div className="block leading-0 text-right" data-cid="n95">
                              <div className="block rounded-[20px]" data-cid="n96">
                                <div className="inline-block relative rounded-[20px] shadow-[var(--clr-9)_0px_40px_100px_0px,var(--color-008)_0px_25px_80px_0px]" data-cid="n97">
                                  {" "}
                                  <div className="inline-block" data-cid="n98">
                                    {" "}
                                    <img className="w-[36.8125rem] h-93.5 inline-block relative max-w-full rounded-[20px] overflow-clip aspect-[auto_1511/960] max-md:w-[22.0625rem] max-md:h-56 md:max-lg:w-180.5 md:max-lg:h-[28.6875rem] 2xl:w-[55.1875rem] 2xl:h-[35.0625rem]" data-cid="n99" data-component="image" alt="" height="960" sizes="(max-width: 1511px) 100vw, 1511px" src="/assets/cloned/images/02eea6b438c5.jpg" srcSet="/assets/cloned/images/02eea6b438c5.jpg 1511w, /assets/cloned/images/4c43d5d4a14c.jpg 300w, /assets/cloned/images/9605e8442364.jpg 1024w, /assets/cloned/images/79579a17ed05.jpg 768w" width="1511" />
                                    {" "}
                                  </div>
                                  {" "}
                                </div>
                                {" "}
                              </div>
                              {" "}
                            </div>
                            <div className="block" data-cid="n100">
                              <div className="h-6 block" data-cid="n101" />
                            </div>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                  </div>
                  {" "}
                  <div className="block relative before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n102" id="contact">
                    <div className="h-full block absolute top-0 inset-x-0" data-cid="n103">
                      <div className="h-full block absolute top-0 inset-x-0 z-1 overflow-hidden" data-cid="n104">
                        <div className="h-full block absolute top-0 inset-x-0 bg-cover" data-cid="n105" />
                      </div>
                    </div>
                    <div className="flex relative z-10 -mx-[0.6875rem] flex-wrap max-md:mx-[-3.3px] md:max-lg:mx-[-6.7px] 2xl:-mx-[0.825rem] after:content-[''] after:block after:w-0 after:h-0" data-cid="n106">
                      <div className="w-full block relative px-[0.7rem] [background-position:50%_50%] max-md:px-[0.2125rem] md:max-lg:px-[6.9px] 2xl:px-[13.5px] after:content-[''] after:block after:w-full after:h-0" data-cid="n107">
                        <div className="h-full block relative" data-cid="n108">
                          <div className="h-full block" data-cid="n109">
                            <div className="block relative pb-[6.4rem] max-md:pb-7.5 md:max-lg:pb-[3.8375rem] 2xl:pb-[9.6rem]" id="fws_6a844afd45577">
                              <div className="mx-auto max-w-3xl overflow-hidden rounded-[10px] shadow-[var(--clr-3)_0px_30px_60px_0px]">
                                <iframe
                                  src="https://forms.clickup.com/9012849900/f/8ckab7c-5032/80PBDE7GWQCQ8LR5EE"
                                  title="Contact Hammer & Anvil Ventures"
                                  className="h-[900px] w-full border-0"
                                  loading="lazy"
                                />
                              </div>
                            </div>
                            {" "}
                            <div className="box-content block relative bg-cover before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n402" id="fws_6a844afd481c1">
                              <div className="h-full block absolute top-0 left-1/2 w-screen -translate-x-1/2" data-cid="n403">
                                <div className="h-full block absolute top-0 inset-x-0 z-1 overflow-hidden" data-cid="n404">
                                  <div className="h-full block absolute top-0 inset-x-0 bg-cover" data-cid="n405" />
                                </div>
                              </div>
                              <div className="flex relative z-10 -mx-[0.6875rem] flex-wrap max-md:mx-[-3.3px] md:max-lg:mx-[-6.7px] 2xl:-mx-[0.825rem] after:content-[''] after:block after:w-0 after:h-0" data-cid="n406">
                                <div className="w-full block relative px-[0.7rem] [background-position:50%_50%] max-md:px-[0.2125rem] md:max-lg:px-[6.9px] 2xl:px-[13.5px] after:content-[''] after:block after:w-full after:h-0" data-cid="n407">
                                  <div className="h-full block relative" data-cid="n408">
                                    <div className="h-full block" data-cid="n409">
                                      <div className="h-full block" data-cid="n410">
                                        <div className="h-full block" data-cid="n411" />
                                      </div>
                                      {" "}
                                    </div>
                                    {" "}
                                  </div>
                                  {" "}
                                </div>
                                {" "}
                              </div>
                            </div>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
            <div className="block relative z-10 text-muted-foreground bg-surface-3" data-cid="n412" id="footer-outer">
              <div className="block" data-cid="n413" id="footer-widgets">
                <div className="block relative max-w-375 px-22.5 max-lg:max-w-[88%] max-md:mx-[22.5px] max-lg:px-0 md:max-lg:mx-[2.875rem] 2xl:mx-52.5 before:content-['_'] before:table before:w-0 before:h-0 before:text-muted-foreground before:text-base before:leading-8 after:content-['_'] after:table after:w-0 after:h-0 after:text-muted-foreground after:text-base after:leading-8" data-cid="n414">
                  <div className="block relative py-[4.6875rem] max-lg:py-[3.4375rem] before:content-['_'] before:table before:w-0 before:h-0 before:text-muted-foreground before:text-base before:leading-8 after:content-['_'] after:table after:w-0 after:h-0 after:text-muted-foreground after:text-base after:leading-8" data-cid="n415">
                    <div className="w-[24.0625rem] h-16 min-h-px block relative float-left z-10 mr-5.5 max-md:w-82.5 max-lg:mb-10 max-md:mr-0 md:max-lg:w-[20.275rem] md:max-lg:h-31.5 md:max-lg:clear-both md:max-lg:mr-[0.9375rem] md:max-lg:p-[0.9375rem] 2xl:w-115.5 2xl:mr-[1.65rem] after:content-[''] after:block after:w-full after:h-0" data-cid="n416">
                      <div className="h-full block" data-cid="n417" id="text-1">
                        <div className="h-full block" data-cid="n418">
                          <p className="h-full block" data-cid="n419">
                            Copyright © 2025 Hammer and Anvil Ventures
                            <br className="inline" data-cid="n420" />
                            {" All rights reserved."}
                          </p>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <div className="w-[214.5px] h-62 min-h-px block relative float-left z-10 mr-5.5 max-md:w-82.5 max-md:h-[15.3rem] max-lg:mb-10 max-lg:mr-0 md:max-lg:w-[20.275rem] md:max-lg:h-69.5 md:max-lg:p-[0.9375rem] 2xl:w-[16.0875rem] 2xl:mr-[1.65rem] after:content-[''] after:block after:w-full after:h-0" data-cid="n421">
                      <div className="block" data-cid="n422" id="nav_menu-1">
                        <h4 className="block mb-5 text-color-004 [font-family:'Cantata_One'] capitalize max-md:leading-[1.8125rem]" data-cid="n423" data-component="heading">
                          Discover
                        </h4>
                        <div className="block" data-cid="n424">
                          <ul className="block [list-style-type:none] list-outside" data-cid="n425" id="menu-main-nav-2">
                            {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids[i]} styles={ListRow2_styles[i]} />)}
                          </ul>
                        </div>
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <div className="w-[214.5px] h-42 min-h-px block relative float-left z-10 mr-5.5 max-md:w-82.5 max-md:h-[10.3rem] max-md:mb-10 max-md:mr-0 md:max-lg:w-[20.275rem] md:max-lg:h-49.5 md:max-lg:clear-both md:max-lg:mr-[0.9375rem] md:max-lg:p-[0.9375rem] 2xl:w-[16.0875rem] 2xl:mr-[1.65rem] after:content-[''] after:block after:w-full after:h-0" data-cid="n436">
                      <div className="block" data-cid="n437" id="categories-1">
                        <h4 className="block mb-5 text-color-004 [font-family:'Cantata_One'] capitalize max-md:leading-[1.8125rem]" data-cid="n438" data-component="heading">
                          Categories
                        </h4>
                        {" "}
                        <ul className="block [list-style-type:none] list-outside" data-cid="n439">
                          {ListRow3_data.map((d, i) => <ListRow3 key={i} d={d} cids={ListRow3_cids[i]} styles={ListRow3_styles[i]} />)}
                        </ul>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <div className="w-[214.5px] h-140 min-h-px block relative float-left z-10 max-md:w-82.5 max-md:h-[24.8rem] md:max-lg:w-[20.275rem] md:max-lg:h-123.5 md:max-lg:p-[0.9375rem] 2xl:w-[16.0875rem] 2xl:h-124 after:content-[''] after:block after:w-full after:h-0" data-cid="n446">
                      <div className="h-full block" data-cid="n447" id="recent-posts-1">
                        <h4 className="block mb-5 text-color-004 [font-family:'Cantata_One'] capitalize max-md:leading-[1.8125rem]" data-cid="n448" data-component="heading">
                          Recent Posts
                        </h4>
                        {" "}
                        <ul className="block [list-style-type:none] list-outside" data-cid="n449">
                          {ListRow4_data.map((d, i) => <ListRow4 key={i} d={d} cids={ListRow4_cids[i]} styles={ListRow4_styles[i]} />)}
                        </ul>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
          <a className="w-[1.8125rem] h-[1.8125rem] block fixed top-[48.1875rem] left-308.5 z-9994 min-w-0 rounded-[200px] overflow-hidden text-background leading-3 text-center bg-color-009 [background-position:50%_50%] bg-no-repeat transform-[matrix(1,0,0,1,0,30.45)] cursor-pointer before:content-['_'] before:block before:absolute before:inset-0 before:z-2 before:w-[1.8125rem] before:h-[1.8125rem] before:text-background before:text-base before:leading-3 before:text-center before:bg-clr-6 before:opacity-0 before: before:origin-[14.5px_14.5px] before:rounded-tl-[100px] after:content-['_'] after:block after:absolute after:inset-0 after:z-1 after:w-[1.8125rem] after:h-[1.8125rem] after:text-background after:text-base after:leading-3 after:text-center after:bg-primary after:transform-[matrix(0,0,0,0,0,0)] after:origin-[14.5px_14.5px] after:rounded-tl-[100px]" data-cid="n458" aria-label="Back to top" href="#" id="to-top">
            <i className="h-[1.8125rem] inline-block relative z-10 max-w-full align-middle [font-family:icomoon] text-sm leading-[1.8125rem] [word-spacing:1px] before:content-[''] before:text-background before:text-sm before:leading-[1.8125rem] before:text-center" data-cid="n459" role="presentation" />
            <i className="h-[1.8125rem] inline-block relative z-10 max-w-full align-middle [font-family:icomoon] text-sm leading-[1.8125rem] [word-spacing:1px] before:content-[''] before:text-background before:text-sm before:leading-[1.8125rem] before:text-center" data-cid="n460" role="presentation" />
          </a>
          {" "}
        </div>
      </div>
    </>
  );
}
