import "./ditto.css";
import ListRow from "./components/list-row";
import Tile from "./components/tile";
import ListRow2 from "./components/list-row2";
import ListRow3 from "./components/list-row3";
import ListRow4 from "./components/list-row4";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { id: "menu-item-5796", href: "/", label: "Home" },
    { id: "menu-item-6208", href: "/our-services", label: "Our Services" },
    { id: "menu-item-5793", href: "/about-us", ariacurrent: "page", label: "About Us" },
    { id: "menu-item-5908", href: "/blog", label: "Blog" },
    { id: "menu-item-5795", href: "/contact-us", label: "Contact Us" }
];
const Tile_data = [
    { value: "*Select a service", text: "*Select a service" },
    { value: "Energy", text: "Energy" },
    { value: "Mining", text: "Mining" },
    { value: "Financial Services", text: "Financial Services" },
    { value: "Hospitality, Food & Beverage", text: "Hospitality, Food & Beverage" },
    { value: "HR/Change Management", text: "HR/Change Management" },
    { value: "Real Estate", text: "Real Estate" },
    { value: "Call Centre Services", text: "Call Centre Services" },
    { value: "IT & Software Development", text: "IT & Software Development" },
    { value: "Corporate Law", text: "Corporate Law" }
];
const ListRow2_data = [
    { href: "/", label: "Home" },
    { href: "/our-services", label: "Our Services" },
    { href: "/about-us", ariacurrent: "page", label: "About Us" },
    { href: "/blog", label: "Blog" },
    { href: "/contact-us", label: "Contact Us" }
];
const ListRow3_data = [
    { href: "https://www.hammerandanvil.co.za/category/energy/", label: "Energy" },
    { href: "https://www.hammerandanvil.co.za/category/renewable-energy/", label: "Renewable Energy" },
    { href: "https://www.hammerandanvil.co.za/category/uncategorized/", label: "Uncategorized" }
];
const ListRow4_data = [
    { href: "/2025/08/11/from-chaos-to-control-building-a-tailored-energy-management-system-for-better-business-outcomes/", label: "From Chaos to Control: Building a Tailored Energy Management System for Better Business Outcomes" },
    { href: "/2025/08/05/unpacking-the-energy-roadmap-a-strategic-asset-for-your-business-in-south-africa/", label: "Unpacking the Energy Roadmap: A Strategic Asset for Your Business in South Africa" },
    { href: "/2025/07/28/building-a-bankable-business-case-for-solar-guide-for-commercial-industrial-business-decision-makers-in-south-africa/", label: "Building a Bankable Business Case for Solar: Guide for Commercial & Industrial business decision makers in South Africa" },
    { href: "/2025/07/22/tariff-optimisation-strategies-for-reducing-electricity-costs-in-the-ci-sector/", label: "Tariff Optimisation: Strategies for Reducing Electricity Costs in the C&I Sector" }
];
const ListRow_cids: string[][] = [
    ["n22", "n23", "n24"],
    ["n25", "n26", "n27"],
    ["n28", "n29", "n30"],
    ["n31", "n32", "n33"],
    ["n34", "n35", "n36"]
];
const Tile_cids: string[][] = [
    ["n318"],
    ["n319"],
    ["n320"],
    ["n321"],
    ["n322"],
    ["n323"],
    ["n324"],
    ["n325"],
    ["n326"],
    ["n327"]
];
const ListRow2_cids: string[][] = [
    ["n361", "n362"],
    ["n363", "n364"],
    ["n365", "n366"],
    ["n367", "n368"],
    ["n369", "n370"]
];
const ListRow3_cids: string[][] = [
    ["n375", "n376"],
    ["n377", "n378"],
    ["n379", "n380"]
];
const ListRow4_cids: string[][] = [
    ["n385", "n386"],
    ["n387", "n388"],
    ["n389", "n390"],
    ["n391", "n392"]
];
const ListRow_styles = [
    { className: "after:w-9.5 after:transform-[matrix(0,0,0,1,0,0)]" },
    { className: "after:w-[4.9375rem] after:transform-[matrix(0,0,0,1,0,0)]" },
    { className: "after:w-14.5 after:" },
    { className: "after:w-7 after:transform-[matrix(0,0,0,1,0,0)]" },
    { className: "after:w-[4.3125rem] after:transform-[matrix(0,0,0,1,0,0)]" }
];
const ListRow2_styles = [
    { className: "pb-1" },
    { className: "py-1" },
    { className: "py-1" },
    { className: "py-1" },
    { className: "py-1" }
];
const ListRow3_styles = [
    { className: "pb-1" },
    { className: "py-1" },
    { className: "py-1" }
];
const ListRow4_styles = [
    { className: "pb-1" },
    { className: "py-1" },
    { className: "py-1" },
    { className: "py-1" }
];

export default function Page() {
  return (
    <>
      <a className="w-px h-px block absolute top-0 left-0 min-w-0 -m-px overflow-hidden text-primary [clip-path:inset(50%)] cursor-pointer" data-cid="n1" href="#ajax-content-wrap">
        Skip to main content
      </a>
      <div className="h-full flex relative z-10 flex-col grow bg-background" data-cid="n2">
        <div className="h-full flex flex-col grow" data-cid="n3">
          {" "}
          <div className="h-33 block bg-background max-lg:h-23.5" data-cid="n4" id="header-space" />
          {" "}
          <div className="h-33 block fixed inset-x-0 z-9998 min-w-0 bg-surface-4 max-lg:h-23.5 max-lg:py-3" data-cid="n5" id="header-outer">
            {" "}
            <header className="h-full block relative z-9998" data-cid="n6" id="top">
              <div className="h-full block relative max-w-375 px-22.5 max-lg:max-w-[88%] max-md:mx-[22.5px] max-lg:px-0 md:max-lg:mx-[2.875rem] 2xl:mx-52.5 before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-8 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-8" data-cid="n7">
                <div className="h-full flex relative max-lg:block before:content-['_'] before:table before:w-0 before:h-33 before:text-foreground before:text-base before:leading-8 max-lg:before:h-0 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-8" data-cid="n8">
                  <div className="w-25 flex relative z-10 max-md:w-82.5 max-lg:block max-lg:float-left max-lg:leading-0 max-lg:text-left md:max-lg:w-[42.2375rem] after:content-[''] after:block after:w-0 after:h-0 max-md:after:w-82.5 md:max-lg:after:w-[42.2375rem]" data-cid="n9">
                    <a className="block relative my-4 self-center text-primary [font-family:'Open_Sans'] text-[1.375rem] font-semibold leading-5.5 tracking-[-1px] cursor-pointer max-lg:inline-block max-lg:align-middle max-lg:static max-lg:right-auto max-lg:bottom-auto max-lg:my-0" data-cid="n10" data-component="link" href="/" id="logo">
                      {" "}
                      <img className="w-25 h-25 block overflow-clip aspect-[auto_300/300] indent-[-9999px] max-lg:w-17.5 max-lg:h-17.5 max-lg:relative" data-cid="n11" data-component="image" alt={"Hammer & Anvil Ventures"} height="300" src="/assets/cloned/images/25371d8dd0a7.png" width="300" />
                      {" "}
                    </a>
                    {" "}
                  </div>
                  {" "}
                  <div className="w-250 h-33 flex left-0 z-1 grow text-center max-lg:w-8 max-lg:h-17.5 max-lg:absolute max-lg:top-0 max-md:left-74.5 max-lg:z-10000 max-lg:items-center max-lg:leading-0 max-lg:text-right md:max-lg:left-[40.2375rem] 2xl:w-305 after:content-[''] after:block after:w-0 after:h-0" data-cid="n12">
                    {" "}
                    <div className="h-full hidden z-10000 min-w-0 max-lg:block max-lg:relative max-lg:pl-2.5 max-lg:align-middle" data-cid="n13">
                      <div className="block transform-[none] max-lg:relative max-lg:top-[2.1875rem] max-lg:-bottom-[2.1875rem] max-lg:text-[1.125rem] max-lg:transform-[matrix(1,0,0,1,0,-10)]" data-cid="n14">
                        <a className="inline text-primary cursor-pointer" data-cid="n15" aria-expanded="false" aria-label="Navigation Menu" href="#slide-out-widget-area" role="button">
                          {" "}
                          <span className="w-5.5 h-px block absolute -m-px overflow-hidden [clip-path:inset(50%)]" data-cid="n16">
                            Menu
                          </span>
                          <span className="w-5.5 h-5 block relative overflow-hidden" data-cid="n17" aria-hidden="true">
                            {" "}
                            <i className="block relative top-[0.5625rem] text-primary text-[0rem] italic leading-0 max-lg:w-5.5 max-lg:-bottom-[0.5625rem] max-lg:leading-[inherit] after:content-[''] after:block after:absolute after:top-0 after:left-0 after:w-5.5 after:h-0.5 after:bg-primary max-lg:after:right-0 max-lg:after:bottom-0 max-lg:after: max-lg:after:origin-[11px_1px]" data-cid="n18">
                              {" "}
                              <i className="w-[1.4rem] h-0.5 block relative text-base leading-5.5 max-lg:w-5.5 before:content-[''] before:block before:absolute before:top-[0.4375rem] before:left-0 before:w-4 before:h-0.5 before:bg-primary max-lg:before:top-1.5 max-lg:before:right-1.5 max-lg:before:-bottom-1.5 after:content-[''] after:block after:absolute after:-top-[0.4375rem] after:left-0 after:w-5.5 after:h-0.5 after:bg-primary max-lg:after:-top-1.5 max-lg:after:right-0 max-lg:after:bottom-1.5" data-cid="n19" />
                              {" "}
                            </i>
                            {" "}
                          </span>
                          {" "}
                        </a>
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <nav className="flex grow max-lg:hidden" data-cid="n20" data-component="nav" aria-label="Main Menu">
                      <ul className="w-full h-33 min-h-px flex z-1 justify-center align-middle leading-px [list-style-type:none] list-outside" data-cid="n21">
                        {ListRow_data.map((d, i) => <ListRow key={i} d={d} cids={ListRow_cids[i]} styles={ListRow_styles[i]} />)}
                      </ul>
                      {" "}
                      <ul className="w-6 h-33 min-h-px flex absolute right-0 z-10 min-w-0 ml-7.5 align-middle leading-px [list-style-type:none] list-outside" data-cid="n37">
                        <li className="flex relative z-100 items-center text-xs leading-3" data-cid="n38">
                          <div className="block z-10" data-cid="n39">
                            <a className="box-content w-6 h-[1.3125rem] block relative z-10 text-muted leading-[1.3125rem] [background-position:100%_0%] bg-no-repeat cursor-pointer" data-cid="n40" data-component="button" aria-expanded="false" aria-label="Navigation Menu" href="#slide-out-widget-area" role="button">
                              {" "}
                              <span className="w-5.5 h-px block absolute z-10 -m-px overflow-hidden [clip-path:inset(50%)]" data-cid="n41">
                                Menu
                                <i className="w-5.5 block relative top-[0.5625rem] right-7.5 -bottom-[0.5625rem] -left-7.5 z-10 -mt-0.5 text-[0rem] italic leading-0 after:content-[''] after:block after:absolute after:inset-y-0 after:-right-[0.025rem] after:left-0 after:w-[1.4rem] after:h-0.5 after:bg-primary after: after:origin-[11.1953px_1px] max-lg:after:w-[1.4rem] max-lg:after:right-auto max-lg:after:bottom-auto max-lg:after:transform-[none] max-lg:after:origin-[initial]" data-cid="n42">
                                  {" "}
                                  <i className="w-[1.4rem] h-0.5 block relative z-10 text-base leading-5.5 before:content-[''] before:block before:absolute before:top-[0.4375rem] before:right-[0.4rem] before:-bottom-[0.4375rem] before:left-0 before:w-4 before:h-0.5 before:bg-primary max-lg:before:w-5.5 max-lg:before:right-auto max-lg:before:bottom-auto after:content-[''] after:block after:absolute after:-top-[0.4375rem] after:bottom-[0.4375rem] after:inset-x-0 after:w-[1.4rem] after:h-0.5 after:bg-primary max-lg:after:w-5.5 max-lg:after:right-auto max-lg:after:bottom-auto" data-cid="n43" />
                                  {" "}
                                </i>
                              </span>
                              <span className="w-5.5 h-[1.3125rem] block relative z-10 overflow-hidden" data-cid="n44" aria-hidden="true">
                                {" "}
                                <i className="w-5.5 block relative top-[0.5625rem] -bottom-[0.5625rem] z-10 text-[0rem] italic leading-0 after:content-[''] after:block after:absolute after:inset-y-0 after:-right-[0.025rem] after:left-0 after:w-[1.4rem] after:h-0.5 after:bg-primary after: after:origin-[11.1953px_1px] max-lg:after:w-[1.4rem] max-lg:after:right-auto max-lg:after:bottom-auto max-lg:after:transform-[none] max-lg:after:origin-[initial]" data-cid="n45">
                                  {" "}
                                  <i className="w-[1.4rem] h-0.5 block relative z-10 text-base leading-5.5 before:content-[''] before:block before:absolute before:top-[0.4375rem] before:right-[0.4rem] before:-bottom-[0.4375rem] before:left-0 before:w-4 before:h-0.5 before:bg-primary max-lg:before:w-5.5 max-lg:before:right-auto max-lg:before:bottom-auto after:content-[''] after:block after:absolute after:-top-[0.4375rem] after:bottom-[0.4375rem] after:inset-x-0 after:w-[1.4rem] after:h-0.5 after:bg-primary max-lg:after:w-5.5 max-lg:after:right-auto max-lg:after:bottom-auto" data-cid="n46" />
                                  {" "}
                                </i>
                                {" "}
                                <i className="w-5.5 block relative top-[0.5625rem] right-7.5 -bottom-[0.5625rem] -left-7.5 z-10 -mt-0.5 text-[0rem] italic leading-0 after:content-[''] after:block after:absolute after:inset-y-0 after:-right-[0.025rem] after:left-0 after:w-[1.4rem] after:h-0.5 after:bg-primary after: after:origin-[11.1953px_1px] max-lg:after:w-[1.4rem] max-lg:after:right-auto max-lg:after:bottom-auto max-lg:after:transform-[none] max-lg:after:origin-[initial]" data-cid="n47">
                                  {" "}
                                  <i className="w-[1.4rem] h-0.5 block relative z-10 text-base leading-5.5 before:content-[''] before:block before:absolute before:top-[0.4375rem] before:right-[0.4rem] before:-bottom-[0.4375rem] before:left-0 before:w-4 before:h-0.5 before:bg-primary max-lg:before:w-5.5 max-lg:before:right-auto max-lg:before:bottom-auto after:content-[''] after:block after:absolute after:-top-[0.4375rem] after:bottom-[0.4375rem] after:inset-x-0 after:w-[1.4rem] after:h-0.5 after:bg-primary max-lg:after:w-5.5 max-lg:after:right-auto max-lg:after:bottom-auto" data-cid="n48" />
                                  {" "}
                                </i>
                              </span>
                              {" "}
                            </a>
                            {" "}
                          </div>
                        </li>
                      </ul>
                      {" "}
                    </nav>
                    {" "}
                    <div className="h-25 block relative -z-100 invisible my-4 leading-0 pointer-events-none max-lg:hidden" data-cid="n49">
                      <img className="w-25 h-25 inline max-w-full overflow-clip aspect-[auto_300/300] pointer-events-none max-lg:hidden" data-cid="n50" alt={"Hammer & Anvil Ventures"} height="300" src="/assets/cloned/images/25371d8dd0a7.png" width="300" />
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </header>
            {" "}
          </div>
          {" "}
          <div className="h-[2687.3px] flex flex-col grow max-md:h-[175.45rem] md:max-lg:h-[160.375rem] 2xl:h-[189.6rem] after:content-[''] after:block after:fixed after:inset-0 after:z-1000 after:w-320 after:h-200 after:bg-clr-0 after:opacity-0 after: after:origin-[640px_400px] max-md:after:w-[23.4375rem] max-md:after:h-203 max-md:after:origin-[187.5px_406px] md:max-lg:after:w-192 md:max-lg:after:h-256 md:max-lg:after:origin-[384px_512px] 2xl:after:w-480 2xl:after:h-270 2xl:after:origin-[960px_540px]" data-cid="n51" id="ajax-content-wrap">
            <div className="h-[1977.3px] block relative z-10 grow bg-background max-md:h-[106.675rem] max-lg:z-11 md:max-lg:h-[102.75rem] 2xl:h-[149.225rem] 2xl:min-h-75.5" data-cid="n52">
              <div className="h-full block relative max-w-375 px-22.5 max-lg:max-w-[88%] max-md:mx-[22.5px] max-lg:px-0 md:max-lg:mx-[2.875rem] 2xl:mx-52.5 before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-8 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-8" data-cid="n53" role="main">
                <div className="h-full block relative before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-8 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-8" data-cid="n54">
                  <div className="w-screen block relative left-1/2 -translate-x-1/2 py-32 bg-cover max-md:py-[2.0625rem] max-lg:[background-position:50%_50%] md:max-lg:py-[4.225rem] 2xl:py-48 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n55" id="fws_6a844acbf2bdd">
                    <div className="h-full block absolute top-0 right-0 left-160 z-2 -ml-160 overflow-hidden max-md:left-[187.5px] max-md:ml-[-187.5px] md:max-lg:left-96 md:max-lg:-ml-96 2xl:left-240 2xl:-ml-240" data-cid="n56">
                      <div className="h-full block absolute top-0 inset-x-0 z-1 overflow-hidden" data-cid="n57">
                        <div className="h-[40.3625rem] block absolute bottom-0 inset-x-0 z-1 bg-clr-7 bg-cover [background-position:50%_50%] bg-no-repeat max-md:h-[27.4875rem] md:max-lg:h-[28.6375rem] 2xl:h-[898.7px]" style={{ backgroundImage: "url(\"/assets/cloned/images/616e4cecc6f0.jpg\")" }} data-cid="n58" />
                      </div>
                      <div className="h-full block absolute top-0 inset-x-0 z-3 opacity-95" style={{ backgroundImage: "linear-gradient(var(--clr-8) 0%, var(--primary) 100%)" }} data-cid="n59" />
                    </div>
                    <div className="flex relative z-10 px-32 flex-wrap text-background max-md:px-[37.5px] md:max-lg:px-[4.8rem] 2xl:px-48 after:content-[''] after:block after:w-0 after:h-0" data-cid="n60">
                      <div className="flex relative items-stretch text-center bg-cover [background-position:50%_50%] max-lg:flex-wrap after:content-[''] after:block after:w-0 after:h-0" data-cid="n61">
                        <div className="flex relative flex-col grow" data-cid="n62">
                          <div className="h-full min-h-full block" data-cid="n63">
                            <div className="block relative z-100 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n64" id="fws_6a844acc0116d">
                              <div className="h-full block absolute top-0 inset-x-0 z-2 overflow-hidden" data-cid="n65">
                                <div className="h-[122.9px] block absolute bottom-0 inset-x-0 z-1 bg-cover max-md:h-[5.5rem] md:max-lg:h-[5.7375rem] 2xl:h-[184.3px]" data-cid="n66" />
                                {" "}
                              </div>
                              <div className="flex relative z-10 flex-wrap after:content-[''] after:block after:w-0 after:h-0" data-cid="n67">
                                <div className="w-full block relative bg-cover [background-position:50%_50%] after:content-[''] after:block after:w-full after:h-0" data-cid="n68">
                                  <div className="h-full block relative" data-cid="n69">
                                    <div className="h-full block" data-cid="n70">
                                      <div className="h-full block text-[6.375rem] leading-[7.0625rem] max-md:text-3xl max-md:leading-[2.0625rem] md:max-lg:text-[3.8125rem] md:max-lg:leading-[4.25rem] 2xl:text-[9.625rem] 2xl:leading-[10.5625rem]" data-cid="n71">
                                        <h1 className="h-full block [font-family:'Cantata_One'] capitalize max-md:text-[2.4375rem] max-md:leading-[3rem] md:max-lg:text-[2.625rem] md:max-lg:leading-[3.25rem]" data-cid="n72" data-component="heading">
                                          <span className="h-full inline-block relative mx-[-5.1px] px-[5.1px] overflow-hidden align-bottom leading-[7.6875rem] max-md:-mx-0.5 max-lg:px-0.5 max-md:leading-[2.9375rem] md:max-lg:mx-[-2.1px] md:max-lg:leading-[3.125rem] 2xl:mx-[-7.7px] 2xl:px-[7.7px] 2xl:leading-[11.5rem]" data-cid="n73">
                                            <span className="h-full inline-block relative align-bottom" data-cid="n74">
                                              W
                                            </span>
                                            <span className="h-full inline-block relative align-bottom" data-cid="n75">
                                              h
                                            </span>
                                            <span className="h-full inline-block relative align-bottom" data-cid="n76">
                                              o
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="h-full inline-block relative mx-[-5.1px] px-[5.1px] overflow-hidden align-bottom leading-[7.6875rem] max-md:-mx-0.5 max-lg:px-0.5 max-md:leading-[2.9375rem] md:max-lg:mx-[-2.1px] md:max-lg:leading-[3.125rem] 2xl:mx-[-7.7px] 2xl:px-[7.7px] 2xl:leading-[11.5rem]" data-cid="n77">
                                            <span className="h-full inline-block relative align-bottom" data-cid="n78">
                                              w
                                            </span>
                                            <span className="h-full inline-block relative align-bottom" data-cid="n79">
                                              e
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="h-full inline-block relative mx-[-5.1px] px-[5.1px] overflow-hidden align-bottom leading-[7.6875rem] max-md:-mx-0.5 max-lg:px-0.5 max-md:leading-[2.9375rem] md:max-lg:mx-[-2.1px] md:max-lg:leading-[3.125rem] 2xl:mx-[-7.7px] 2xl:px-[7.7px] 2xl:leading-[11.5rem]" data-cid="n80">
                                            <span className="h-full inline-block relative align-bottom" data-cid="n81">
                                              a
                                            </span>
                                            <span className="h-full inline-block relative align-bottom" data-cid="n82">
                                              r
                                            </span>
                                            <span className="h-full inline-block relative align-bottom" data-cid="n83">
                                              e
                                            </span>
                                          </span>
                                          {" "}
                                        </h1>
                                      </div>
                                      {" "}
                                    </div>
                                    {" "}
                                  </div>
                                  {" "}
                                </div>
                                {" "}
                              </div>
                            </div>
                            <div className="block relative py-2.5 max-md:py-[0.1875rem] md:max-lg:py-1.5 2xl:py-[0.9625rem] before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n84" id="fws_6a844acc01a1e">
                              <div className="h-full block absolute top-0 inset-x-0 z-2 overflow-hidden" data-cid="n85">
                                <div className="h-[120.5px] block absolute bottom-0 inset-x-0 z-1 bg-cover max-md:h-[7.5625rem] md:max-lg:h-[127.3px] 2xl:h-[130.7px]" data-cid="n86" />
                                {" "}
                              </div>
                              <div className="flex relative z-10 px-64 flex-wrap max-md:px-[4.6875rem] md:max-lg:px-[9.6rem] 2xl:px-96 after:content-[''] after:block after:w-0 after:h-0" data-cid="n87">
                                <div className="w-full block relative bg-cover [background-position:50%_50%] after:content-[''] after:block after:w-full after:h-0" data-cid="n88">
                                  <div className="block relative" data-cid="n89">
                                    <div className="block" data-cid="n90">
                                      <div className="block" data-cid="n91">
                                        <div className="w-px h-12.5 block my-[1.5625rem] mx-auto py-[1.5625rem] bg-background max-lg:h-[1.5625rem] max-lg:pb-0" data-cid="n92" />
                                      </div>
                                      {" "}
                                    </div>
                                    {" "}
                                  </div>
                                  {" "}
                                </div>
                                {" "}
                              </div>
                            </div>
                            <div className="block relative before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n93" id="fws_6a844acc020bb">
                              <div className="h-full block absolute top-0 inset-x-0 z-2 overflow-hidden" data-cid="n94">
                                <div className="h-[106.5px] block absolute bottom-0 inset-x-0 z-1 bg-cover max-md:h-[15.3rem] md:max-lg:h-[11.5rem] 2xl:h-[159.7px]" data-cid="n95" />
                                {" "}
                              </div>
                              <div className="flex relative z-10 px-[15.3625rem] flex-wrap max-md:px-6 md:max-lg:px-[5.7625rem] 2xl:px-[23.0375rem] after:content-[''] after:block after:w-0 after:h-0" data-cid="n96">
                                <div className="block relative bg-cover [background-position:50%_50%] after:content-[''] after:block after:w-full after:h-0" data-cid="n97">
                                  <div className="h-full block relative" data-cid="n98">
                                    <div className="h-full block" data-cid="n99">
                                      <div className="h-full block text-[1.0625rem] leading-[1.6875rem] max-md:leading-[1.625rem] max-md:[font-size:inherit] md:max-lg:text-lg md:max-lg:leading-[1.8125rem] 2xl:text-[1.5625rem] 2xl:leading-10" data-cid="n100">
                                        <p className="h-full block" data-cid="n101">
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n102">
                                            <span className="inline-block relative align-bottom" data-cid="n103">
                                              With
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n104">
                                            <span className="inline-block relative align-bottom" data-cid="n105">
                                              years
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n106">
                                            <span className="inline-block relative align-bottom" data-cid="n107">
                                              of
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n108">
                                            <span className="inline-block relative align-bottom" data-cid="n109">
                                              industry
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n110">
                                            <span className="inline-block relative align-bottom" data-cid="n111">
                                              experience
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n112">
                                            <span className="inline-block relative align-bottom" data-cid="n113">
                                              and
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n114">
                                            <span className="inline-block relative align-bottom" data-cid="n115">
                                              a
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n116">
                                            <span className="inline-block relative align-bottom" data-cid="n117">
                                              team
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n118">
                                            <span className="inline-block relative align-bottom" data-cid="n119">
                                              of
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n120">
                                            <span className="inline-block relative align-bottom" data-cid="n121">
                                              dedicated
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="h-[1.6625rem] inline-block relative overflow-hidden align-bottom max-md:h-[1.6rem] md:max-lg:h-[1.8rem] 2xl:h-10" data-cid="n122">
                                            <span className="h-full inline-block relative align-bottom" data-cid="n123">
                                              professionals,
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n124">
                                            <span className="inline-block relative align-bottom" data-cid="n125">
                                              Hammer
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n126">
                                            <span className="inline-block relative align-bottom" data-cid="n127">
                                              {"&"}
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n128">
                                            <span className="inline-block relative align-bottom" data-cid="n129">
                                              Anvil
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n130">
                                            <span className="inline-block relative align-bottom" data-cid="n131">
                                              is
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n132">
                                            <span className="inline-block relative align-bottom" data-cid="n133">
                                              committed
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n134">
                                            <span className="inline-block relative align-bottom" data-cid="n135">
                                              to
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n136">
                                            <span className="inline-block relative align-bottom" data-cid="n137">
                                              helping
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n138">
                                            <span className="inline-block relative align-bottom" data-cid="n139">
                                              you
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n140">
                                            <span className="inline-block relative align-bottom" data-cid="n141">
                                              achieve
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n142">
                                            <span className="inline-block relative align-bottom" data-cid="n143">
                                              operational
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n144">
                                            <span className="inline-block relative align-bottom" data-cid="n145">
                                              excellence.
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n146">
                                            <span className="inline-block relative align-bottom" data-cid="n147">
                                              We
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n148">
                                            <span className="inline-block relative align-bottom" data-cid="n149">
                                              take
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n150">
                                            <span className="inline-block relative align-bottom" data-cid="n151">
                                              a
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n152">
                                            <span className="inline-block relative align-bottom" data-cid="n153">
                                              consultative
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n154">
                                            <span className="inline-block relative align-bottom" data-cid="n155">
                                              approach
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n156">
                                            <span className="inline-block relative align-bottom" data-cid="n157">
                                              to
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n158">
                                            <span className="inline-block relative align-bottom" data-cid="n159">
                                              every
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n160">
                                            <span className="inline-block relative align-bottom" data-cid="n161">
                                              project,
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n162">
                                            <span className="inline-block relative align-bottom" data-cid="n163">
                                              tailoring
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n164">
                                            <span className="inline-block relative align-bottom" data-cid="n165">
                                              our
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n166">
                                            <span className="inline-block relative align-bottom" data-cid="n167">
                                              solutions
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n168">
                                            <span className="inline-block relative align-bottom" data-cid="n169">
                                              to
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n170">
                                            <span className="inline-block relative align-bottom" data-cid="n171">
                                              meet
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n172">
                                            <span className="inline-block relative align-bottom" data-cid="n173">
                                              your
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n174">
                                            <span className="inline-block relative align-bottom" data-cid="n175">
                                              unique
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n176">
                                            <span className="inline-block relative align-bottom" data-cid="n177">
                                              goals.
                                            </span>
                                          </span>
                                          {" "}
                                        </p>
                                      </div>
                                      {" "}
                                    </div>
                                    {" "}
                                  </div>
                                  {" "}
                                </div>
                                {" "}
                              </div>
                            </div>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                  </div>
                  {" "}
                  <div className="box-content block relative pt-[6.4rem] pb-[1.6rem] bg-cover max-md:pt-[2.0625rem] max-md:pb-[7.5px] md:max-lg:pt-[4.225rem] md:max-lg:pb-[0.9625rem] 2xl:pt-[9.6rem] 2xl:pb-[2.4rem] before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n178" id="fws_6a844acc02967">
                    <div className="h-full block absolute top-0 left-1/2 w-screen -translate-x-1/2" data-cid="n179">
                      <div className="h-full block absolute top-0 inset-x-0 z-1 overflow-hidden" data-cid="n180">
                        <div className="h-full block absolute top-0 inset-x-0 bg-cover" data-cid="n181" />
                      </div>
                    </div>
                    <div className="h-[11.3125rem] flex relative z-10 -mx-[0.6875rem] flex-wrap max-md:h-[21.8rem] max-md:mx-[-3.3px] md:max-lg:h-[15.3375rem] md:max-lg:mx-[-6.7px] 2xl:h-[14.5375rem] 2xl:-mx-[0.825rem] after:content-[''] after:block after:w-0 after:h-0" data-cid="n182">
                      <div className="w-full block relative mb-[-67.3px] px-[0.7rem] [background-position:50%_50%] max-md:-mb-5 max-md:px-[0.2125rem] md:max-lg:-mb-[2.5875rem] md:max-lg:px-[6.9px] 2xl:-mb-[5.05rem] 2xl:px-[13.5px] after:content-[''] after:block after:w-full after:h-0" data-cid="n183">
                        <div className="h-full block relative" data-cid="n184">
                          <div className="h-full block" data-cid="n185">
                            <div className="h-full block relative before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n186" id="team">
                              <div className="h-full block absolute top-0 inset-x-0" data-cid="n187">
                                <div className="h-full block absolute top-0 inset-x-0 bg-cover" data-cid="n188" />
                                {" "}
                              </div>
                              <div className="h-full flex relative z-10 -mx-[0.6875rem] flex-wrap max-md:mx-[-3.3px] md:max-lg:mx-[-6.7px] 2xl:-mx-[0.825rem] after:content-[''] after:block after:w-0 after:h-0" data-cid="n189">
                                <div className="w-full block relative px-[0.7rem] text-center [background-position:50%_50%] max-md:px-[0.2125rem] md:max-lg:px-[6.9px] 2xl:px-[13.5px] after:content-[''] after:block after:w-full after:h-0" data-cid="n190">
                                  <div className="h-full block relative" data-cid="n191">
                                    <div className="h-full block" data-cid="n192">
                                      <h2 className="block mb-2.5 [font-family:'Cantata_One'] text-[2.5625rem] leading-[3.0625rem] max-md:text-4xl max-md:leading-[2.75rem] md:max-lg:text-[2.375rem] md:max-lg:leading-[2.875rem] 2xl:text-5xl 2xl:leading-14.5" data-cid="n193" data-component="heading">
                                        Our mission is simple
                                      </h2>
                                      <div className="block" data-cid="n194">
                                        <div className="w-16 h-0.5 block my-8 mx-auto bg-primary" data-cid="n195" />
                                      </div>
                                      <div className="flex mb-6 justify-center text-sm leading-[1.4375rem] max-md:leading-[1.625rem] max-md:[font-size:inherit] md:max-lg:text-lg md:max-lg:leading-[1.8125rem] 2xl:text-[1.3125rem] 2xl:leading-[2.125rem]" data-cid="n196">
                                        <p className="w-full max-w-175 block" data-cid="n197">
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n198">
                                            <span className="inline-block relative align-bottom" data-cid="n199">
                                              To
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n200">
                                            <span className="inline-block relative align-bottom" data-cid="n201">
                                              empower
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n202">
                                            <span className="inline-block relative align-bottom" data-cid="n203">
                                              businesses
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n204">
                                            <span className="inline-block relative align-bottom" data-cid="n205">
                                              to
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n206">
                                            <span className="inline-block relative align-bottom" data-cid="n207">
                                              innovate,
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n208">
                                            <span className="inline-block relative align-bottom" data-cid="n209">
                                              evolve,
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n210">
                                            <span className="inline-block relative align-bottom" data-cid="n211">
                                              and
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n212">
                                            <span className="inline-block relative align-bottom" data-cid="n213">
                                              succeed
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n214">
                                            <span className="inline-block relative align-bottom" data-cid="n215">
                                              in
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n216">
                                            <span className="inline-block relative align-bottom" data-cid="n217">
                                              their
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n218">
                                            <span className="inline-block relative align-bottom" data-cid="n219">
                                              respective
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n220">
                                            <span className="inline-block relative align-bottom" data-cid="n221">
                                              fields.
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n222">
                                            <span className="inline-block relative align-bottom" data-cid="n223">
                                              Whether
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n224">
                                            <span className="inline-block relative align-bottom" data-cid="n225">
                                              you’re
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n226">
                                            <span className="inline-block relative align-bottom" data-cid="n227">
                                              navigating
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="h-[22.5px] inline-block relative overflow-hidden align-bottom max-md:h-[1.6rem] md:max-lg:h-[1.8rem] 2xl:h-[2.1125rem]" data-cid="n228">
                                            <span className="h-full inline-block relative align-bottom" data-cid="n229">
                                              transformation,
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n230">
                                            <span className="inline-block relative align-bottom" data-cid="n231">
                                              optimising
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n232">
                                            <span className="inline-block relative align-bottom" data-cid="n233">
                                              operations,
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n234">
                                            <span className="inline-block relative align-bottom" data-cid="n235">
                                              or
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n236">
                                            <span className="inline-block relative align-bottom" data-cid="n237">
                                              looking
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n238">
                                            <span className="inline-block relative align-bottom" data-cid="n239">
                                              to
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n240">
                                            <span className="inline-block relative align-bottom" data-cid="n241">
                                              excel
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n242">
                                            <span className="inline-block relative align-bottom" data-cid="n243">
                                              in
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n244">
                                            <span className="inline-block relative align-bottom" data-cid="n245">
                                              your
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n246">
                                            <span className="inline-block relative align-bottom" data-cid="n247">
                                              market,
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n248">
                                            <span className="inline-block relative align-bottom" data-cid="n249">
                                              we’re
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n250">
                                            <span className="inline-block relative align-bottom" data-cid="n251">
                                              here
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n252">
                                            <span className="inline-block relative align-bottom" data-cid="n253">
                                              to
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n254">
                                            <span className="inline-block relative align-bottom" data-cid="n255">
                                              power
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n256">
                                            <span className="inline-block relative align-bottom" data-cid="n257">
                                              your
                                            </span>
                                          </span>
                                          {" "}
                                          <span className="inline-block relative overflow-hidden align-bottom" data-cid="n258">
                                            <span className="inline-block relative align-bottom" data-cid="n259">
                                              success.
                                            </span>
                                          </span>
                                          {" "}
                                        </p>
                                      </div>
                                      <div className="block" data-cid="n260">
                                        <div className="h-16 block" data-cid="n261" />
                                      </div>
                                      {" "}
                                    </div>
                                    {" "}
                                  </div>
                                  {" "}
                                </div>
                                {" "}
                              </div>
                            </div>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                  </div>
                  {" "}
                  <div className="block relative before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n262" id="fws_6a844acc04277">
                    <div className="h-full block absolute top-0 inset-x-0" data-cid="n263">
                      <div className="h-full block absolute top-0 inset-x-0 z-1 overflow-hidden" data-cid="n264">
                        <div className="h-full block absolute top-0 inset-x-0 bg-cover" data-cid="n265" />
                      </div>
                    </div>
                    <div className="flex relative z-10 -mx-[0.6875rem] flex-wrap max-md:mx-[-3.3px] md:max-lg:mx-[-6.7px] 2xl:-mx-[0.825rem] after:content-[''] after:block after:w-0 after:h-0" data-cid="n266">
                      <div className="w-full block relative px-[0.7rem] [background-position:50%_50%] max-md:px-[0.2125rem] md:max-lg:px-[6.9px] 2xl:px-[13.5px] after:content-[''] after:block after:w-full after:h-0" data-cid="n267">
                        <div className="h-full block relative" data-cid="n268">
                          <div className="h-full block" data-cid="n269">
                            <div className="box-content block relative z-100 py-[3.2rem] bg-cover max-md:py-[0.4125rem] md:max-lg:py-[13.5px] 2xl:py-[4.8rem] before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n270" id="fws_6a844acc04f05">
                              <div className="h-full block absolute top-0 left-1/2 w-screen -translate-x-1/2 overflow-hidden" data-cid="n271">
                                <div className="h-full block absolute top-0 inset-x-0 z-1 overflow-hidden" data-cid="n272">
                                  <div className="h-full block absolute top-0 inset-x-0 bg-cover" data-cid="n273" />
                                </div>
                              </div>
                              <div className="flex relative z-10 -mx-[0.6875rem] flex-wrap max-md:mx-[-3.3px] md:max-lg:mx-[-6.7px] 2xl:-mx-[0.825rem] after:content-[''] after:block after:w-0 after:h-0" data-cid="n274">
                                <div className="w-[11.6875rem] block relative px-[0.7rem] [background-position:50%_50%] max-md:w-[10.5125rem] max-lg:mb-[1.5625rem] max-md:px-[0.2125rem] md:max-lg:w-[13.4375rem] md:max-lg:px-[6.9px] 2xl:w-[224.3px] 2xl:px-[13.5px] after:content-[''] after:block after:w-full after:h-0" data-cid="n275">
                                  <div className="block relative" data-cid="n276">
                                    <div className="block" data-cid="n277" />
                                    {" "}
                                  </div>
                                  {" "}
                                </div>
                                {" "}
                                <div className="w-[747.7px] block relative px-[0.7rem] [background-position:50%_50%] max-md:w-[336.5px] max-lg:mb-[1.5625rem] max-md:px-[0.2125rem] md:max-lg:w-[43.0625rem] md:max-lg:px-[6.9px] 2xl:w-[56.075rem] 2xl:px-[13.5px] after:content-[''] after:block after:w-full after:h-0" data-cid="n278">
                                  <div className="h-full block relative" data-cid="n279">
                                    <div className="h-full block" data-cid="n280">
                                      <div className="block relative mb-6 pb-[3.175rem] max-md:pb-[1.4375rem] md:max-lg:pb-[47.3px] 2xl:pb-[3.8125rem] before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n281" id="fws_6a844acc05738">
                                        <div className="h-full block absolute top-0 inset-x-0 overflow-hidden" data-cid="n282">
                                          <div className="h-full block absolute top-0 inset-x-0 bg-cover" data-cid="n283" />
                                          {" "}
                                        </div>
                                        <div className="flex relative z-10 -mx-[0.45rem] flex-wrap max-md:mx-[-3.3px] md:max-lg:mx-[-6.7px] 2xl:mx-[-8.7px] after:content-[''] after:block after:w-0 after:h-0" data-cid="n284">
                                          <div className="w-full block relative px-[0.4625rem] text-center [background-position:50%_50%] max-md:px-[0.2125rem] md:max-lg:px-[6.9px] 2xl:px-[8.9px] after:content-[''] after:block after:w-full after:h-0" data-cid="n285">
                                            <div className="h-full block relative" data-cid="n286">
                                              <div className="h-full block" data-cid="n287">
                                                <div className="h-full block" data-cid="n288">
                                                  <div className="h-full block" data-cid="n289">
                                                    <h5 className="block mb-[0.4375rem] [font-family:'Cantata_One'] text-xl leading-7" data-cid="n290" data-component="heading">
                                                      Let’s Innovate
                                                    </h5>
                                                    {" "}
                                                    <h2 className="block [font-family:'Cantata_One'] text-[2.5625rem] leading-[3.0625rem] max-md:text-4xl max-md:leading-[2.75rem] md:max-lg:text-[2.375rem] md:max-lg:leading-[2.875rem] 2xl:text-5xl 2xl:leading-14.5" data-cid="n291" data-component="heading">
                                                      Message Us
                                                    </h2>
                                                    {" "}
                                                  </div>
                                                  {" "}
                                                </div>
                                                {" "}
                                              </div>
                                              {" "}
                                            </div>
                                            {" "}
                                          </div>
                                          {" "}
                                        </div>
                                      </div>
                                      <div className="block relative before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n292" id="fws_6a844acc05dd3">
                                        <div className="h-full block absolute top-0 inset-x-0 overflow-hidden" data-cid="n293">
                                          <div className="h-full block absolute top-0 inset-x-0 bg-cover" data-cid="n294" />
                                          {" "}
                                        </div>
                                        <div className="h-[32.5625rem] flex relative z-10 -mx-[0.45rem] flex-wrap max-md:h-[37.5625rem] max-md:mx-[-3.3px] md:max-lg:h-[33.7375rem] md:max-lg:mx-[-6.7px] 2xl:h-[30.8rem] 2xl:mx-[-8.7px] after:content-[''] after:block after:w-0 after:h-0" data-cid="n295">
                                          <div className="w-full block relative -mb-[11.5625rem] px-[0.4625rem] rounded-[10px] [background-position:50%_50%] max-md:-mb-[5.25rem] max-md:px-[0.2125rem] md:max-lg:-mb-[10.7625rem] md:max-lg:px-[6.9px] 2xl:-mb-[13.875rem] 2xl:px-[8.9px] after:content-[''] after:block after:w-full after:h-0" data-cid="n296">
                                            <div className="h-full block relative p-[2.0625rem] rounded-[10px] max-md:p-[22.5px] md:max-lg:p-9 2xl:p-[2.3375rem]" data-cid="n297">
                                              <div className="w-[45.3125rem] h-full block absolute top-0 left-0 -z-1 rounded-[10px] overflow-hidden shadow-[var(--clr-3)_0px_60px_135px_0px,var(--clr-3)_0px_15px_65px_0px] pointer-events-none max-md:w-[20.6rem] md:max-lg:w-[42.1875rem] 2xl:w-[54.375rem]" data-cid="n298">
                                                <div className="h-full block absolute top-0 inset-x-0 -z-1 bg-background pointer-events-none" data-cid="n299" />
                                              </div>
                                              {" "}
                                              <div className="block" data-cid="n300">
                                                <div className="block" data-cid="n301">
                                                  <div className="block" data-cid="n302">
                                                    <div className="block" data-cid="n303" dir="ltr" id="wpcf7-f6-p92-o1" lang="en-ZA">
                                                      <div className="w-px h-px block absolute -m-px overflow-hidden [clip-path:inset(50%)]" data-cid="n304">
                                                        {" "}
                                                      </div>
                                                      {" "}
                                                      <form className="block" data-cid="n305" aria-label="Contact form">
                                                        {" "}
                                                        <p className="block pb-6" data-cid="n306">
                                                          <span className="block relative text-color-007" data-cid="n307">
                                                            <input className="w-full h-11.5 border-b-2 border-solid border-b-surface inline-block relative p-2.5 overflow-clip text-color-006 text-sm leading-6 bg-color-005 cursor-text" data-cid="n308" data-component="input" aria-invalid="false" aria-required="true" name="FullName" placeholder="*Enter your name and surname" type="text" defaultValue="" />
                                                          </span>
                                                          {" "}
                                                        </p>
                                                        {" "}
                                                        <p className="block pb-6" data-cid="n309">
                                                          <span className="block relative text-color-007" data-cid="n310">
                                                            <input className="w-full h-11.5 border-b-2 border-solid border-b-surface inline-block relative p-2.5 overflow-clip text-color-006 text-sm leading-6 bg-color-005 cursor-text" data-cid="n311" data-component="input" aria-invalid="false" aria-required="true" name="Email" placeholder="*Enter your contact email address" type="email" defaultValue="" />
                                                          </span>
                                                          {" "}
                                                        </p>
                                                        {" "}
                                                        <p className="block pb-6" data-cid="n312">
                                                          <span className="block relative text-color-007" data-cid="n313">
                                                            <input className="w-full h-11.5 border-b-2 border-solid border-b-surface inline-block relative p-2.5 overflow-clip text-color-006 text-sm leading-6 bg-color-005 cursor-text" data-cid="n314" data-component="input" aria-invalid="false" name="Number" placeholder="Enter your contact number" type="tel" defaultValue="" />
                                                          </span>
                                                          {" "}
                                                        </p>
                                                        {" "}
                                                        <p className="block pb-6" data-cid="n315">
                                                          <span className="block relative text-color-007" data-cid="n316">
                                                            <select className="w-full h-[2.5625rem] border-b-2 border-solid border-b-surface inline-block relative p-2.5 items-center text-color-006 text-sm leading-[1.0625rem] whitespace-pre text-nowrap bg-color-005 cursor-default" data-cid="n317" data-component="select" aria-invalid="false" aria-required="true" name="Service">
                                                              {Tile_data.map((d, i) => <Tile key={i} d={d} cids={Tile_cids[i]} />)}
                                                            </select>
                                                          </span>
                                                          {" "}
                                                        </p>
                                                        {" "}
                                                        <p className="block pb-6" data-cid="n328">
                                                          <span className="block relative text-color-007" data-cid="n329">
                                                            <textarea className="w-full h-70.5 border-b-2 border-solid border-b-surface inline-block relative max-w-full p-5 overflow-auto text-color-006 text-sm leading-6 whitespace-pre-wrap [overflow-wrap:break-word] bg-color-005 cursor-text" data-cid="n330" data-component="textarea" aria-invalid="false" name="YourMessage" placeholder="Type your message" />
                                                          </span>
                                                          {" "}
                                                        </p>
                                                        {" "}
                                                        <p className="block" data-cid="n331">
                                                          <input className="w-23.5 h-[3.0625rem] inline-block py-[0.9375rem] px-5.5 rounded-[200px] overflow-clip text-background font-semibold leading-[1.1875rem] text-center capitalize whitespace-pre text-nowrap bg-primary cursor-pointer" data-cid="n332" data-component="button" type="submit" value="Submit" />
                                                          <span className="w-6 h-6 inline-block relative invisible opacity-75 mx-6 rounded-[100%] text-color-007 bg-clr-4 before:content-[''] before:block before:absolute before:top-1 before:right-3.5 before:bottom-3.5 before:left-1 before:w-1.5 before:h-1.5 before:bg-clr-5 before:transform-[matrix(0.905664,-0.423996,0.423996,0.905664,0,0)] before:origin-[8px_8px] before:rounded-tl-[100%] max-md:before:transform-[matrix(-0.980324,-0.197395,0.197395,-0.980324,0,0)] md:max-lg:before:transform-[matrix(0.867776,0.496956,-0.496956,0.867776,0,0)] 2xl:before:transform-[matrix(0.679769,0.733426,-0.733426,0.679769,0,0)]" data-cid="n333" />
                                                          {" "}
                                                        </p>
                                                        {" "}
                                                      </form>
                                                      {" "}
                                                    </div>
                                                    {" "}
                                                  </div>
                                                  {" "}
                                                </div>
                                                {" "}
                                              </div>
                                              {" "}
                                            </div>
                                            {" "}
                                          </div>
                                          {" "}
                                        </div>
                                      </div>
                                      {" "}
                                    </div>
                                    {" "}
                                  </div>
                                  {" "}
                                </div>
                                {" "}
                                <div className="w-[11.6875rem] block relative px-[0.7rem] [background-position:50%_50%] max-md:w-[10.5125rem] max-md:px-[0.2125rem] md:max-lg:w-[13.4375rem] md:max-lg:px-[6.9px] 2xl:w-[224.3px] 2xl:px-[13.5px] after:content-[''] after:block after:w-full after:h-0" data-cid="n334">
                                  <div className="block relative" data-cid="n335">
                                    <div className="block" data-cid="n336" />
                                    {" "}
                                  </div>
                                  {" "}
                                </div>
                                {" "}
                              </div>
                            </div>
                            {" "}
                            <div className="box-content block relative bg-cover before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n337" id="fws_6a844acc16fb7">
                              <div className="h-full block absolute top-0 left-1/2 w-screen -translate-x-1/2" data-cid="n338">
                                <div className="h-full block absolute top-0 inset-x-0 z-1 overflow-hidden" data-cid="n339">
                                  <div className="h-full block absolute top-0 inset-x-0 bg-cover" data-cid="n340" />
                                </div>
                              </div>
                              <div className="flex relative z-10 -mx-[0.6875rem] flex-wrap max-md:mx-[-3.3px] md:max-lg:mx-[-6.7px] 2xl:-mx-[0.825rem] after:content-[''] after:block after:w-0 after:h-0" data-cid="n341">
                                <div className="w-full block relative px-[0.7rem] [background-position:50%_50%] max-md:px-[0.2125rem] md:max-lg:px-[6.9px] 2xl:px-[13.5px] after:content-[''] after:block after:w-full after:h-0" data-cid="n342">
                                  <div className="h-full block relative" data-cid="n343">
                                    <div className="h-full block" data-cid="n344">
                                      <div className="h-full block" data-cid="n345">
                                        <div className="h-full block" data-cid="n346" />
                                      </div>
                                      {" "}
                                    </div>
                                    {" "}
                                  </div>
                                  {" "}
                                </div>
                                {" "}
                              </div>
                            </div>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
            <div className="block relative z-10 text-muted-foreground bg-surface-3" data-cid="n347" id="footer-outer">
              <div className="block" data-cid="n348" id="footer-widgets">
                <div className="block relative max-w-375 px-22.5 max-lg:max-w-[88%] max-md:mx-[22.5px] max-lg:px-0 md:max-lg:mx-[2.875rem] 2xl:mx-52.5 before:content-['_'] before:table before:w-0 before:h-0 before:text-muted-foreground before:text-base before:leading-8 after:content-['_'] after:table after:w-0 after:h-0 after:text-muted-foreground after:text-base after:leading-8" data-cid="n349">
                  <div className="block relative py-[4.6875rem] max-lg:py-[3.4375rem] before:content-['_'] before:table before:w-0 before:h-0 before:text-muted-foreground before:text-base before:leading-8 after:content-['_'] after:table after:w-0 after:h-0 after:text-muted-foreground after:text-base after:leading-8" data-cid="n350">
                    <div className="w-[24.0625rem] h-16 min-h-px block relative float-left z-10 mr-5.5 max-md:w-82.5 max-lg:mb-10 max-md:mr-0 md:max-lg:w-[20.275rem] md:max-lg:h-31.5 md:max-lg:clear-both md:max-lg:mr-[0.9375rem] md:max-lg:p-[0.9375rem] 2xl:w-115.5 2xl:mr-[1.65rem] after:content-[''] after:block after:w-full after:h-0" data-cid="n351">
                      <div className="h-full block" data-cid="n352" id="text-1">
                        <div className="h-full block" data-cid="n353">
                          <p className="h-full block" data-cid="n354">
                            Copyright © 2025 Hammer and Anvil Ventures
                            <br className="inline" data-cid="n355" />
                            {" All rights reserved."}
                          </p>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <div className="w-[214.5px] h-62 min-h-px block relative float-left z-10 mr-5.5 max-md:w-82.5 max-md:h-[15.3rem] max-lg:mb-10 max-lg:mr-0 md:max-lg:w-[20.275rem] md:max-lg:h-69.5 md:max-lg:p-[0.9375rem] 2xl:w-[16.0875rem] 2xl:mr-[1.65rem] after:content-[''] after:block after:w-full after:h-0" data-cid="n356">
                      <div className="block" data-cid="n357" id="nav_menu-1">
                        <h4 className="block mb-5 text-color-004 [font-family:'Cantata_One'] capitalize max-md:leading-[1.8125rem]" data-cid="n358" data-component="heading">
                          Discover
                        </h4>
                        <div className="block" data-cid="n359">
                          <ul className="block [list-style-type:none] list-outside" data-cid="n360" id="menu-main-nav-2">
                            {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids[i]} styles={ListRow2_styles[i]} />)}
                          </ul>
                        </div>
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <div className="w-[214.5px] h-42 min-h-px block relative float-left z-10 mr-5.5 max-md:w-82.5 max-md:h-[10.3rem] max-md:mb-10 max-md:mr-0 md:max-lg:w-[20.275rem] md:max-lg:h-49.5 md:max-lg:clear-both md:max-lg:mr-[0.9375rem] md:max-lg:p-[0.9375rem] 2xl:w-[16.0875rem] 2xl:mr-[1.65rem] after:content-[''] after:block after:w-full after:h-0" data-cid="n371">
                      <div className="block" data-cid="n372" id="categories-1">
                        <h4 className="block mb-5 text-color-004 [font-family:'Cantata_One'] capitalize max-md:leading-[1.8125rem]" data-cid="n373" data-component="heading">
                          Categories
                        </h4>
                        {" "}
                        <ul className="block [list-style-type:none] list-outside" data-cid="n374">
                          {ListRow3_data.map((d, i) => <ListRow3 key={i} d={d} cids={ListRow3_cids[i]} styles={ListRow3_styles[i]} />)}
                        </ul>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <div className="w-[214.5px] h-140 min-h-px block relative float-left z-10 max-md:w-82.5 max-md:h-[24.8rem] md:max-lg:w-[20.275rem] md:max-lg:h-123.5 md:max-lg:p-[0.9375rem] 2xl:w-[16.0875rem] 2xl:h-124 after:content-[''] after:block after:w-full after:h-0" data-cid="n381">
                      <div className="h-full block" data-cid="n382" id="recent-posts-1">
                        <h4 className="block mb-5 text-color-004 [font-family:'Cantata_One'] capitalize max-md:leading-[1.8125rem]" data-cid="n383" data-component="heading">
                          Recent Posts
                        </h4>
                        {" "}
                        <ul className="block [list-style-type:none] list-outside" data-cid="n384">
                          {ListRow4_data.map((d, i) => <ListRow4 key={i} d={d} cids={ListRow4_cids[i]} styles={ListRow4_styles[i]} />)}
                        </ul>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
          <a className="w-[1.8125rem] h-[1.8125rem] block fixed top-[48.1875rem] left-308.5 z-9994 min-w-0 rounded-[200px] overflow-hidden text-background leading-3 text-center bg-color-009 [background-position:50%_50%] bg-no-repeat transform-[matrix(1,0,0,1,0,30.45)] cursor-pointer before:content-['_'] before:block before:absolute before:inset-0 before:z-2 before:w-[1.8125rem] before:h-[1.8125rem] before:text-background before:text-base before:leading-3 before:text-center before:bg-clr-6 before:opacity-0 before: before:origin-[14.5px_14.5px] before:rounded-tl-[100px] after:content-['_'] after:block after:absolute after:inset-0 after:z-1 after:w-[1.8125rem] after:h-[1.8125rem] after:text-background after:text-base after:leading-3 after:text-center after:bg-primary after:transform-[matrix(0,0,0,0,0,0)] after:origin-[14.5px_14.5px] after:rounded-tl-[100px]" data-cid="n393" aria-label="Back to top" href="#" id="to-top">
            <i className="h-[1.8125rem] inline-block relative z-10 max-w-full align-middle [font-family:icomoon] text-sm leading-[1.8125rem] [word-spacing:1px] before:content-[''] before:text-background before:text-sm before:leading-[1.8125rem] before:text-center" data-cid="n394" role="presentation" />
            <i className="h-[1.8125rem] inline-block relative z-10 max-w-full align-middle [font-family:icomoon] text-sm leading-[1.8125rem] [word-spacing:1px] before:content-[''] before:text-background before:text-sm before:leading-[1.8125rem] before:text-center" data-cid="n395" role="presentation" />
          </a>
          {" "}
        </div>
      </div>
    </>
  );
}
