import "./ditto.css";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import FeatureCard from "./components/feature-card";
import FeatureCard2 from "./components/feature-card2";
import FeatureCard3 from "./components/feature-card3";
import FeatureCard4 from "./components/feature-card4";
import ListRow3 from "./components/list-row3";
import HomeContactForm from "@/components/home-contact-form";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { id: "menu-item-5796", ariacurrent: "page", href: "/", label: "Home" },
    { id: "menu-item-6208", href: "/our-services", label: "Our Services" },
    { id: "menu-item-5793", href: "/about-us", label: "About Us" },
    { id: "menu-item-5908", href: "/blog", label: "Blog" },
    { id: "menu-item-5795", href: "/contact-us", label: "Contact Us" }
];
const ListRow2_data = [
    { text: "Energy" },
    { text: "Mining" },
    { text: "Financial Services" },
    { text: "Group Events" },
    { text: "Hospitality, Food & Beverage" },
    { text: "HR/Change Management" },
    { text: "Real Estate" },
    { text: "Call Centre Services" },
    { text: "IT & Software Development" },
    { text: "Corporate Law" }
];
const FeatureCard_data = [
    { title: "Energy Solutions", title2: "Financial Services", title3: "Hospitality, Food & Beverage" },
    { title: "HR & Change Management", title2: "Real Estate", title3: "Mining" },
    { title: "Call Centre Services", title2: "IT & Software Development", title3: "Corporate Law" }
];
const FeatureCard2_data = [
    { title: "Industry Expertise", description: "Our team includes seasoned professionals with a track record of success from each sector we serve." },
    { title: "Tailored Approach", description: "We understand that every business is unique, and we customise our solutions to meet your needs across diverse industries." },
    { title: "Commitment to Excellence", description: "We are driven by results and dedicated to your success." },
    { title: "Sustainability Focus", description: "We prioritise eco-friendly practices in every project." }
];
const FeatureCard3_data = [
    { title: "End-to-End Support", description: "From consultation to implementation, we’re with you every step of the way." },
    { title: "Innovative Thinking", description: "We embrace the latest technologies and trends to drive results." },
    { title: "Collaborative Approach", description: "Your goals are our goals. We work closely with you to achieve success." },
    { title: "Proven Track Record", description: "A portfolio of satisfied clients speaks to our ability to deliver on promises." }
];
const FeatureCard4_data = [
    { title: "Understanding Your Needs", description: "We begin with a thorough consultation to identify your challenges and goals." },
    { title: "Customised Strategy Development", description: "Our team crafts a bespoke plan tailored to your business objectives." },
    { title: "Seamless Implementation", description: "We execute the plan, ensuring minimal disruption to your operations." },
    { title: "Continuous Support", description: "Post-implementation, we provide ongoing support to adapt to evolving needs." }
];
const ListRow3_data = [
    { ariacurrent: "page", href: "/", label: "Home" },
    { href: "/our-services", label: "Our Services" },
    { href: "/about-us", label: "About Us" },
    { href: "/blog", label: "Blog" },
    { href: "/contact-us", label: "Contact Us" }
];
const ListRow_cids: string[][] = [
    ["n21", "n22", "n23"],
    ["n24", "n25", "n26"],
    ["n27", "n28", "n29"],
    ["n30", "n31", "n32"],
    ["n33", "n34", "n35"]
];
const ListRow2_cids: string[][] = [
    ["n122"],
    ["n123"],
    ["n124"],
    ["n125"],
    ["n126"],
    ["n127"],
    ["n128"],
    ["n129"],
    ["n130"],
    ["n131"]
];
const FeatureCard_cids: string[][] = [
    ["n141", "n142", "n143", "n144", "n145", "n146", "n147", "n148", "n149", "n150", "n151", "n152", "n153", "n154", "n155", "n156", "n157", "n158", "n159", "n160", "n161"],
    ["n162", "n163", "n164", "n165", "n166", "n167", "n168", "n169", "n170", "n171", "n172", "n173", "n174", "n175", "n176", "n177", "n178", "n179", "n180", "n181", "n182"],
    ["n183", "n184", "n185", "n186", "n187", "n188", "n189", "n190", "n191", "n192", "n193", "n194", "n195", "n196", "n197", "n198", "n199", "n200", "n201", "n202", "n203"]
];
const FeatureCard2_cids: string[][] = [
    ["n222", "n223", "n224", "n225", "n226", "n227", "n228"],
    ["n229", "n230", "n231", "n232", "n233", "n234", "n235"],
    ["n236", "n237", "n238", "n239", "n240", "n241", "n242"],
    ["n243", "n244", "n245", "n246", "n247", "n248", "n249"]
];
const FeatureCard3_cids: string[][] = [
    ["n254", "n255", "n256", "n257", "n258", "n259", "n260"],
    ["n261", "n262", "n263", "n264", "n265", "n266", "n267"],
    ["n268", "n269", "n270", "n271", "n272", "n273", "n274"],
    ["n275", "n276", "n277", "n278", "n279", "n280", "n281"]
];
const FeatureCard4_cids: string[][] = [
    ["n307", "n308", "n309", "n310", "n311", "n312", "n313"],
    ["n314", "n315", "n316", "n317", "n318", "n319", "n320"],
    ["n321", "n322", "n323", "n324", "n325", "n326", "n327"],
    ["n328", "n329", "n330", "n331", "n332", "n333", "n334"]
];
const ListRow3_cids: string[][] = [
    ["n568", "n569"],
    ["n570", "n571"],
    ["n572", "n573"],
    ["n574", "n575"],
    ["n576", "n577"]
];
const ListRow_styles = [
    { className2: "after:w-9.5 after:" },
    { className: "opacity-75", className2: "after:w-[4.9375rem] after:transform-[matrix(0,0,0,1,0,0)]" },
    { className: "opacity-75", className2: "after:w-14.5 after:transform-[matrix(0,0,0,1,0,0)]" },
    { className: "opacity-75", className2: "after:w-7 after:transform-[matrix(0,0,0,1,0,0)]" },
    { className: "opacity-75", className2: "after:w-[4.3125rem] after:transform-[matrix(0,0,0,1,0,0)]" }
];
const FeatureCard_styles = [
    { className: "h-full", className2: "h-[12.375rem] mt-12.5 max-md:h-[11.8125rem]", className3: "bg-color-012 after:bg-color-012", className4: "before:content-['']", className5: "h-[12.375rem] max-md:h-[11.8125rem] md:max-lg:h-[18.2375rem] 2xl:h-[13.225rem]", className6: "bg-primary after:bg-primary", className7: "before:content-['']", className8: "h-[14.375rem] max-md:h-[13.6125rem] md:max-lg:h-[18.2375rem] 2xl:h-[15.225rem]", className9: "bg-color-012 after:bg-color-012", className10: "before:content-['']" },
    { className: "h-[42.4875rem] max-md:h-[714.3px] md:max-lg:h-[1007.5px] 2xl:h-[691.7px]", className2: "h-[14.375rem] max-md:h-[13.6125rem]", className3: "bg-primary after:bg-primary", className4: "before:content-['']", className6: "bg-color-012 after:bg-color-012", className7: "before:content-['']", className9: "bg-primary after:bg-primary", className10: "before:content-['']" },
    { className: "h-[49.6125rem] max-md:h-[49.5625rem] md:max-lg:h-[1057.5px] 2xl:h-[773.7px]", className2: "h-[12.375rem] mt-12.5 max-md:h-[13.6125rem]", className3: "bg-color-012 after:bg-color-012", className4: "before:content-['']", className5: "h-[14.375rem] max-md:h-[13.6125rem] md:max-lg:h-[18.2375rem] 2xl:h-[13.225rem]", className6: "bg-primary after:bg-primary", className7: "before:content-['']", className8: "h-[12.375rem] max-md:h-[11.8125rem] md:max-lg:h-[18.2375rem] 2xl:h-[11.225rem]", className9: "bg-color-012 after:bg-color-012", className10: "before:content-['']" }
];
const FeatureCard2_styles = [
    { className: "max-lg:h-[9.3125rem] max-md:mb-[1.5625rem] md:max-lg:clear-both md:max-lg:mb-3.5", className2: "pr-[33.5px] max-md:pr-[42.9px] md:max-lg:pr-[2.6875rem] 2xl:pr-10" },
    { className: "max-lg:h-[9.3125rem] max-md:mb-[1.5625rem] md:max-lg:mb-3.5", className2: "pr-[1.6125rem] max-lg:pr-[2.0625rem] 2xl:pr-[1.9375rem]" },
    { className: "max-lg:h-[7.3125rem] max-md:mb-[1.5625rem] md:max-lg:clear-both md:max-lg:mb-3.5", className2: "pr-[33.5px] max-md:pr-[42.9px] md:max-lg:pr-[2.6875rem] 2xl:pr-10" },
    { className: "max-md:h-[7.3125rem] md:max-lg:h-[8.175rem]", className2: "pr-[1.6125rem] max-lg:pr-[2.0625rem] 2xl:pr-[1.9375rem]" }
];
const FeatureCard3_styles = [
    { className: "max-lg:h-[7.3125rem] max-md:mb-[1.5625rem] md:max-lg:clear-both md:max-lg:mb-3.5", className2: "pr-[33.5px] max-md:pr-[42.9px] md:max-lg:pr-[2.6875rem] 2xl:pr-10" },
    { className: "max-lg:h-[7.3125rem] max-md:mb-[1.5625rem] md:max-lg:mb-3.5", className2: "pr-[1.6125rem] max-lg:pr-[2.0625rem] 2xl:pr-[1.9375rem]" },
    { className: "max-lg:h-[7.3125rem] max-md:mb-[1.5625rem] md:max-lg:clear-both md:max-lg:mb-3.5", className2: "pr-[33.5px] max-md:pr-[42.9px] md:max-lg:pr-[2.6875rem] 2xl:pr-10" },
    { className: "max-md:h-[7.3125rem] md:max-lg:h-[8.175rem]", className2: "pr-[1.6125rem] max-lg:pr-[2.0625rem] 2xl:pr-[1.9375rem]" }
];
const FeatureCard4_styles = [
    { className: "max-md:h-[7.3125rem] max-md:mb-[1.5625rem] md:max-lg:h-[9.0625rem] md:max-lg:clear-both md:max-lg:mb-[0.8375rem]", className2: "pr-[32.5px] max-md:pr-[2.5875rem] md:max-lg:pr-[2.6125rem] 2xl:pr-[2.4375rem]" },
    { className: "max-lg:h-[9.0625rem] max-md:mb-[1.5625rem] md:max-lg:mb-[0.8375rem]", className2: "pr-[1.5625rem] max-lg:pr-8 2xl:pr-[1.875rem]" },
    { className: "max-lg:h-[7.3125rem] max-md:mb-[1.5625rem] md:max-lg:clear-both md:max-lg:mb-[0.8375rem]", className2: "pr-[32.5px] max-md:pr-[2.5875rem] md:max-lg:pr-[2.6125rem] 2xl:pr-[2.4375rem]" },
    { className: "max-md:h-[9.3125rem] md:max-lg:h-[8.15rem]", className2: "pr-[1.5625rem] max-lg:pr-8 2xl:pr-[1.875rem]" }
];
const ListRow3_styles = [
    { className: "pb-1" },
    { className: "py-1" },
    { className: "py-1" },
    { className: "py-1" },
    { className: "py-1" }
];

export default function Page() {
  return (
    <>
      <a className="w-px h-px block absolute top-0 left-0 min-w-0 -m-px overflow-hidden text-primary [clip-path:inset(50%)] cursor-pointer" data-cid="n1" href="#ajax-content-wrap">
        Skip to main content
      </a>
      <div className="h-full flex relative z-10 flex-col grow bg-background" data-cid="n2">
        <div className="h-full flex flex-col grow" data-cid="n3">
          {" "}
          <div className="h-33 block fixed inset-x-0 z-9998 min-w-0 max-lg:h-23.5 max-lg:py-3" data-cid="n4" id="header-outer">
            {" "}
            <header className="h-full block relative z-9998" data-cid="n5" id="top">
              <div className="h-full block relative max-w-375 px-22.5 max-lg:max-w-[88%] max-md:mx-[22.5px] max-lg:px-0 md:max-lg:mx-[2.875rem] 2xl:mx-52.5 before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-8 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-8" data-cid="n6">
                <div className="h-full flex relative max-lg:block before:content-['_'] before:table before:w-0 before:h-33 before:text-foreground before:text-base before:leading-8 max-lg:before:h-0 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-8" data-cid="n7">
                  <div className="w-25 flex relative z-10 max-md:w-82.5 max-lg:block max-lg:float-left max-lg:leading-0 max-lg:text-left md:max-lg:w-[42.2375rem] after:content-[''] after:block after:w-0 after:h-0 max-md:after:w-82.5 md:max-lg:after:w-[42.2375rem]" data-cid="n8">
                    <a className="block relative my-4 self-center text-background [font-family:'Open_Sans'] text-[1.375rem] font-semibold leading-5.5 tracking-[-1px] cursor-pointer max-lg:inline-block max-lg:align-middle max-lg:static max-lg:right-auto max-lg:bottom-auto max-lg:my-0" data-cid="n9" data-component="link" href="/" id="logo">
                      {" "}
                      <img className="w-25 h-25 block absolute top-0 overflow-clip aspect-[auto_300/300] indent-[-9999px] max-lg:w-17.5 max-lg:h-17.5" data-cid="n10" data-component="image" alt={"Hammer & Anvil Ventures"} height="300" src="/assets/cloned/images/8204e3557a53.png" width="300" />
                      {" "}
                    </a>
                    {" "}
                  </div>
                  {" "}
                  <div className="w-250 h-33 flex left-0 z-1 grow text-center max-lg:w-8 max-lg:h-17.5 max-lg:absolute max-lg:top-0 max-md:left-74.5 max-lg:z-10000 max-lg:items-center max-lg:leading-0 max-lg:text-right md:max-lg:left-[40.2375rem] 2xl:w-305 after:content-[''] after:block after:w-0 after:h-0" data-cid="n11">
                    {" "}
                    <div className="h-full hidden z-10000 min-w-0 max-lg:block max-lg:relative max-lg:pl-2.5 max-lg:align-middle" data-cid="n12">
                      <div className="block transform-[none] max-lg:relative max-lg:top-[2.1875rem] max-lg:-bottom-[2.1875rem] max-lg:text-[1.125rem] max-lg:transform-[matrix(1,0,0,1,0,-10)]" data-cid="n13">
                        <a className="inline text-primary cursor-pointer" data-cid="n14" aria-expanded="false" aria-label="Navigation Menu" href="#slide-out-widget-area" role="button">
                          {" "}
                          <span className="w-5.5 h-px block absolute -m-px overflow-hidden [clip-path:inset(50%)]" data-cid="n15">
                            Menu
                          </span>
                          <span className="w-5.5 h-5 block relative overflow-hidden" data-cid="n16" aria-hidden="true">
                            {" "}
                            <i className="block relative top-[0.5625rem] text-primary text-[0rem] italic leading-0 max-lg:w-5.5 max-lg:-bottom-[0.5625rem] max-lg:leading-[inherit] after:content-[''] after:block after:absolute after:top-0 after:left-0 after:w-5.5 after:h-0.5 after:bg-background max-lg:after:right-0 max-lg:after:bottom-0 max-lg:after: max-lg:after:origin-[11px_1px]" data-cid="n17">
                              {" "}
                              <i className="w-[1.4rem] h-0.5 block relative text-base leading-5.5 max-lg:w-5.5 before:content-[''] before:block before:absolute before:top-[0.4375rem] before:left-0 before:w-4 before:h-0.5 before:bg-background max-lg:before:top-1.5 max-lg:before:right-1.5 max-lg:before:-bottom-1.5 after:content-[''] after:block after:absolute after:-top-[0.4375rem] after:left-0 after:w-5.5 after:h-0.5 after:bg-background max-lg:after:-top-1.5 max-lg:after:right-0 max-lg:after:bottom-1.5" data-cid="n18" />
                              {" "}
                            </i>
                            {" "}
                          </span>
                          {" "}
                        </a>
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <nav className="flex grow max-lg:hidden" data-cid="n19" data-component="nav" aria-label="Main Menu">
                      <ul className="w-full h-33 min-h-px flex z-1 justify-center align-middle leading-px [list-style-type:none] list-outside" data-cid="n20">
                        {ListRow_data.map((d, i) => <ListRow key={i} d={d} cids={ListRow_cids[i]} styles={ListRow_styles[i]} />)}
                      </ul>
                      {" "}
                      <ul className="w-6 h-33 min-h-px flex absolute right-0 z-10 min-w-0 ml-7.5 align-middle leading-px [list-style-type:none] list-outside" data-cid="n36">
                        <li className="flex relative z-100 items-center text-xs leading-3" data-cid="n37">
                          <div className="block z-10" data-cid="n38">
                            <a className="box-content w-6 h-[1.3125rem] block relative z-10 text-muted leading-[1.3125rem] [background-position:100%_0%] bg-no-repeat cursor-pointer" data-cid="n39" data-component="button" aria-expanded="false" aria-label="Navigation Menu" href="#slide-out-widget-area" role="button">
                              {" "}
                              <span className="w-5.5 h-px block absolute z-10 -m-px overflow-hidden [clip-path:inset(50%)]" data-cid="n40">
                                Menu
                                <i className="w-5.5 block relative top-[0.5625rem] right-7.5 -bottom-[0.5625rem] -left-7.5 z-10 -mt-0.5 text-[0rem] italic leading-0 after:content-[''] after:block after:absolute after:inset-y-0 after:-right-[0.025rem] after:left-0 after:w-[1.4rem] after:h-0.5 after:bg-background after:opacity-75 after: after:origin-[11.1953px_1px] max-lg:after:w-[1.4rem] max-lg:after:right-auto max-lg:after:bottom-auto max-lg:after:transform-[none] max-lg:after:origin-[initial]" data-cid="n41">
                                  {" "}
                                  <i className="w-[1.4rem] h-0.5 block relative z-10 opacity-75 text-base leading-5.5 before:content-[''] before:block before:absolute before:top-[0.4375rem] before:right-[0.4rem] before:-bottom-[0.4375rem] before:left-0 before:w-4 before:h-0.5 before:bg-background max-lg:before:w-5.5 max-lg:before:right-auto max-lg:before:bottom-auto after:content-[''] after:block after:absolute after:-top-[0.4375rem] after:bottom-[0.4375rem] after:inset-x-0 after:w-[1.4rem] after:h-0.5 after:bg-background max-lg:after:w-5.5 max-lg:after:right-auto max-lg:after:bottom-auto" data-cid="n42" />
                                  {" "}
                                </i>
                              </span>
                              <span className="w-5.5 h-[1.3125rem] block relative z-10 overflow-hidden" data-cid="n43" aria-hidden="true">
                                {" "}
                                <i className="w-5.5 block relative top-[0.5625rem] -bottom-[0.5625rem] z-10 text-[0rem] italic leading-0 after:content-[''] after:block after:absolute after:inset-y-0 after:-right-[0.025rem] after:left-0 after:w-[1.4rem] after:h-0.5 after:bg-background after:opacity-75 after: after:origin-[11.1953px_1px] max-lg:after:w-[1.4rem] max-lg:after:right-auto max-lg:after:bottom-auto max-lg:after:transform-[none] max-lg:after:origin-[initial]" data-cid="n44">
                                  {" "}
                                  <i className="w-[1.4rem] h-0.5 block relative z-10 opacity-75 text-base leading-5.5 before:content-[''] before:block before:absolute before:top-[0.4375rem] before:right-[0.4rem] before:-bottom-[0.4375rem] before:left-0 before:w-4 before:h-0.5 before:bg-background max-lg:before:w-5.5 max-lg:before:right-auto max-lg:before:bottom-auto after:content-[''] after:block after:absolute after:-top-[0.4375rem] after:bottom-[0.4375rem] after:inset-x-0 after:w-[1.4rem] after:h-0.5 after:bg-background max-lg:after:w-5.5 max-lg:after:right-auto max-lg:after:bottom-auto" data-cid="n45" />
                                  {" "}
                                </i>
                                {" "}
                                <i className="w-5.5 block relative top-[0.5625rem] right-7.5 -bottom-[0.5625rem] -left-7.5 z-10 -mt-0.5 text-[0rem] italic leading-0 after:content-[''] after:block after:absolute after:inset-y-0 after:-right-[0.025rem] after:left-0 after:w-[1.4rem] after:h-0.5 after:bg-background after:opacity-75 after: after:origin-[11.1953px_1px] max-lg:after:w-[1.4rem] max-lg:after:right-auto max-lg:after:bottom-auto max-lg:after:transform-[none] max-lg:after:origin-[initial]" data-cid="n46">
                                  {" "}
                                  <i className="w-[1.4rem] h-0.5 block relative z-10 opacity-75 text-base leading-5.5 before:content-[''] before:block before:absolute before:top-[0.4375rem] before:right-[0.4rem] before:-bottom-[0.4375rem] before:left-0 before:w-4 before:h-0.5 before:bg-background max-lg:before:w-5.5 max-lg:before:right-auto max-lg:before:bottom-auto after:content-[''] after:block after:absolute after:-top-[0.4375rem] after:bottom-[0.4375rem] after:inset-x-0 after:w-[1.4rem] after:h-0.5 after:bg-background max-lg:after:w-5.5 max-lg:after:right-auto max-lg:after:bottom-auto" data-cid="n47" />
                                  {" "}
                                </i>
                              </span>
                              {" "}
                            </a>
                            {" "}
                          </div>
                        </li>
                      </ul>
                      {" "}
                    </nav>
                    {" "}
                    <div className="h-25 block relative -z-100 invisible my-4 leading-0 pointer-events-none max-lg:hidden" data-cid="n48">
                      <img className="w-25 h-25 inline max-w-full overflow-clip aspect-[auto_300/300] pointer-events-none max-lg:hidden" data-cid="n49" alt={"Hammer & Anvil Ventures"} height="300" src="/assets/cloned/images/25371d8dd0a7.png" width="300" />
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </header>
            {" "}
          </div>
          {" "}
          <div className="h-full flex flex-col grow after:content-[''] after:block after:fixed after:inset-0 after:z-1000 after:w-320 after:h-200 after:bg-clr-0 after:opacity-0 after: after:origin-[640px_400px] max-md:after:w-[23.4375rem] max-md:after:h-203 max-md:after:origin-[187.5px_406px] md:max-lg:after:w-192 md:max-lg:after:h-256 md:max-lg:after:origin-[384px_512px] 2xl:after:w-480 2xl:after:h-270 2xl:after:origin-[960px_540px]" data-cid="n50" id="ajax-content-wrap">
            <div className="h-[437.35rem] min-h-22.5 block relative z-10 grow bg-background max-md:h-[794.2875rem] max-lg:z-11 md:max-lg:h-2784.5 md:max-lg:min-h-25.5 2xl:h-[477.9125rem] 2xl:min-h-108.5" data-cid="n51">
              <div className="h-full block relative max-w-375 px-22.5 max-lg:max-w-[88%] max-md:mx-[22.5px] max-lg:px-0 md:max-lg:mx-[2.875rem] 2xl:mx-52.5 before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-8 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-8" data-cid="n52" role="main">
                <div className="h-full block relative before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-8 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-8" data-cid="n53">
                  <div className="box-content block relative pt-[11.2rem] pb-[14.4rem] bg-cover max-md:pt-[52.5px] max-md:pb-[67.5px] md:max-lg:pt-[107.5px] md:max-lg:pb-[8.6375rem] 2xl:pt-[16.8rem] 2xl:pb-[21.6rem] before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n54" id="fws_6a8446775ec92">
                    <div className="h-full block absolute top-0 left-1/2 w-screen -translate-x-1/2 overflow-hidden" data-cid="n55">
                      <div className="h-full block absolute top-0 inset-x-0 z-1 overflow-hidden" data-cid="n56">
                        <div className="h-full block absolute top-0 inset-x-0 bg-cover [background-position:50%_0%] bg-no-repeat" style={{ backgroundImage: "url(\"/assets/cloned/images/11fc7d30e3c2.jpg\")" }} data-cid="n57" />
                      </div>
                      <div className="h-full block absolute top-0 inset-x-0 z-3" style={{ backgroundImage: "linear-gradient(0deg, var(--clr-1) 0%, var(--clr-2) 49%)" }} data-cid="n58" />
                    </div>
                    <div className="w-320 h-62.5 block absolute bottom-0 left-137.5 z-3 -ml-160 max-md:w-[23.4375rem] max-md:left-[10.3125rem] max-md:ml-[-187.5px] md:max-lg:w-192 md:max-lg:left-[21.125rem] md:max-lg:-ml-96 2xl:w-480 2xl:left-165 2xl:-ml-240" data-cid="n59">
                      <svg className="w-320 h-62.5 block absolute -bottom-px overflow-hidden max-md:w-[23.4375rem] max-md:h-[5.1875rem] md:max-lg:w-192 md:max-lg:h-47 2xl:w-480" data-cid="n60" data-component="image" aria-hidden="true" fill="#ffffff" viewBox="0 0 1000 100" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none">
                        <path d="M 0 0 c 0 0 200 50 500 50 s 500 -50 500 -50 v 101 h -1000 v -100 z" />
                      </svg>
                    </div>
                    <div className="flex relative z-10 -mx-[0.6875rem] flex-wrap text-background max-md:mx-[-3.3px] max-md:pt-20 md:max-lg:mx-[-6.7px] md:max-lg:pt-17.5 2xl:-mx-[0.825rem] after:content-[''] after:block after:w-0 after:h-0" data-cid="n61">
                      <div className="w-[11.6875rem] block relative px-[0.7rem] [background-position:50%_50%] max-md:w-[168.3px] max-lg:mb-[1.5625rem] max-md:px-[0.2125rem] md:max-lg:w-[13.4375rem] md:max-lg:px-[6.9px] 2xl:w-[14.025rem] 2xl:px-[13.5px] after:content-[''] after:block after:w-full after:h-0" data-cid="n62">
                        <div className="block relative" data-cid="n63">
                          <div className="block" data-cid="n64" />
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                      <div className="w-187 block relative px-[0.7rem] text-center [background-position:50%_50%] max-md:w-[21.0375rem] max-lg:mb-[1.5625rem] max-md:px-[0.2125rem] md:max-lg:w-[689.3px] md:max-lg:px-[6.9px] 2xl:w-[56.1rem] 2xl:px-[13.5px] after:content-[''] after:block after:w-full after:h-0" data-cid="n65">
                        <div className="h-full block relative p-[0.6875rem] max-md:p-1 md:max-lg:p-1.5 2xl:p-[12.5px]" data-cid="n66">
                          <div className="h-full block" data-cid="n67">
                            <div className="block mb-[0.9375rem] [animation-name:fadeInUp] [animation-duration:1s] [animation-fill-mode:both] max-lg:[animation-name:initial] max-lg:[animation-duration:initial] max-lg:[animation-fill-mode:initial]" data-cid="n68">
                              <div className="block" data-cid="n69">
                                <h5 className="block [font-family:'Cantata_One'] text-xl leading-7" data-cid="n70" data-component="heading">
                                  {"Hammer & Anvil Ventures"}
                                </h5>
                                {" "}
                              </div>
                              {" "}
                            </div>
                            {" "}
                            <div className="block mb-6" data-cid="n71">
                              <div className="h-[6.9375rem] block relative overflow-hidden max-md:h-[12.025rem] md:max-lg:h-[6.475rem] 2xl:h-37" data-cid="n72">
                                <div className="h-full block" data-cid="n73">
                                  <h1 className="h-full block [font-family:'Cantata_One'] text-[2.8125rem] leading-[3.5rem] capitalize max-md:text-[2.4375rem] max-md:leading-[3rem] md:max-lg:text-[2.625rem] md:max-lg:leading-[3.25rem] 2xl:text-6xl 2xl:leading-18.5" data-cid="n74" data-component="heading" data-ditto-animate="fade-up">
                                    Empowering businesses, driving excellence.
                                  </h1>
                                  {" "}
                                </div>
                                {" "}
                              </div>
                            </div>
                            <a className="h-12.5 border-2 border-solid border-color-013 inline-block relative mt-[1.5625rem] mb-12 py-[0.8125rem] px-[2.1875rem] rounded-[200px] text-sm font-semibold leading-5 capitalize cursor-pointer" data-cid="n75" data-component="button" href="#contact" role="button">
                              <span className="inline-block relative whitespace-nowrap" data-cid="n76">
                                Get in touch
                              </span>
                            </a>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                      <div className="w-[11.6875rem] block relative px-[0.7rem] [background-position:50%_50%] max-md:w-[168.3px] max-md:px-[0.2125rem] md:max-lg:w-[13.4375rem] md:max-lg:px-[6.9px] 2xl:w-[14.025rem] 2xl:px-[13.5px] after:content-[''] after:block after:w-full after:h-0" data-cid="n77">
                        <div className="block relative" data-cid="n78">
                          <div className="block" data-cid="n79" />
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                  </div>
                  {" "}
                  <div className="box-content block relative pt-[3.2rem] pb-[1.6rem] bg-cover max-md:pt-[0.9375rem] max-md:pb-[7.5px] md:max-lg:pt-[30.7px] md:max-lg:pb-[0.9625rem] 2xl:pt-[4.8rem] 2xl:pb-[2.4rem] before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n80" id="fws_6a84467760462">
                    <div className="h-full block absolute top-0 left-1/2 w-screen -translate-x-1/2" data-cid="n81">
                      <div className="h-full block absolute top-0 inset-x-0 z-1 overflow-hidden" data-cid="n82">
                        <div className="h-full block absolute top-0 inset-x-0 bg-cover" data-cid="n83" />
                      </div>
                    </div>
                    <div className="flex relative z-10 -mx-[0.6875rem] flex-wrap max-md:mx-[-3.3px] md:max-lg:mx-[-6.7px] 2xl:-mx-[0.825rem] after:content-[''] after:block after:w-0 after:h-0" data-cid="n84">
                      <div className="w-93.5 flex relative px-[0.7rem] items-stretch [background-position:50%_50%] max-md:w-[21.0375rem] max-lg:mb-[1.5625rem] max-md:px-[0.2125rem] max-lg:flex-wrap md:max-lg:w-[689.3px] md:max-lg:px-[6.9px] 2xl:w-[28.05rem] 2xl:px-[13.5px] after:content-[''] after:block after:w-0 after:h-0" data-cid="n85">
                        <div className="h-[693.5px] flex relative pr-5.5 flex-col justify-center grow max-md:h-108 max-md:pr-[11.3px] md:max-lg:h-68 md:max-lg:pr-4.5 2xl:h-[52rem] 2xl:pr-[24.9px]" data-cid="n86">
                          <div className="h-118 min-h-px block max-md:h-108 md:max-lg:h-68 2xl:h-98" data-cid="n87">
                            <div className="block mb-6" data-cid="n88">
                              <div className="block" data-cid="n89">
                                <h3 className="block [font-family:'Cantata_One'] text-[1.6875rem] leading-8.5 max-lg:text-[1.625rem] max-lg:leading-[inherit] 2xl:text-[2rem] 2xl:leading-10" data-cid="n90" data-component="heading" data-ditto-animate="fade-up">
                                  Your One-Stop Partner for Business Excellence Across Industries
                                </h3>
                                {" "}
                              </div>
                              {" "}
                            </div>
                            {" "}
                            <div className="block" data-cid="n91">
                              <div className="block" data-cid="n92">
                                <p className="block pb-6" data-cid="n93">
                                  {"At Hammer & Anvil, we understand that no two businesses are alike. That’s why we’ve created a multifaceted service company designed to help organisations thrive across a wide spectrum of industries."}
                                </p>
                                {" "}
                                <p className="block" data-cid="n94">
                                  Whether you need cutting-edge energy solutions, transformative HR strategies, or advanced IT systems, we have the expertise to deliver measurable results.
                                </p>
                                {" "}
                              </div>
                              {" "}
                            </div>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                      <div className="w-187 flex relative px-[0.7rem] items-stretch [background-position:50%_50%] max-md:w-[21.0375rem] max-md:px-[0.2125rem] max-lg:flex-wrap md:max-lg:w-[689.3px] md:max-lg:px-[6.9px] 2xl:w-[56.1rem] 2xl:px-[13.5px] after:content-[''] after:block after:w-0 after:h-0" data-cid="n95">
                        <div className="flex relative flex-col justify-center grow" data-cid="n96">
                          <div className="h-full min-h-px block" data-cid="n97">
                            <div className="h-full block leading-0" data-cid="n98">
                              <div className="w-full h-full block" data-cid="n99">
                                <div className="h-full block relative" data-cid="n100" data-ditto-animate="fade-right">
                                  {" "}
                                  <div className="h-full block" data-cid="n101">
                                    {" "}
                                    <img className="w-full h-full block relative object-cover" data-cid="n102" data-component="image" alt="Buildings in Sandton City" height="960" sizes="(max-width: 1511px) 100vw, 1511px" src="/assets/cloned/images/f3c9d3b337ff.jpg" srcSet="/assets/cloned/images/f3c9d3b337ff.jpg 1511w, /assets/cloned/images/382f52c3531c.jpg 300w, /assets/cloned/images/482726dc7de1.jpg 1024w, /assets/cloned/images/a671dff03b24.jpg 768w" width="1511" />
                                    {" "}
                                  </div>
                                  {" "}
                                </div>
                                {" "}
                              </div>
                              {" "}
                            </div>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                  </div>
                  {" "}
                  <div className="box-content block relative py-[4.8rem] bg-cover max-md:py-[22.5px] md:max-lg:py-[2.875rem] 2xl:py-[7.2rem] before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n103" id="fws_6a84467761908">
                    <div className="h-full block absolute top-0 left-1/2 w-screen -translate-x-1/2" data-cid="n104">
                      <div className="h-full block absolute top-0 inset-x-0 z-1 overflow-hidden" data-cid="n105">
                        <div className="h-full block absolute top-0 inset-x-0 bg-cover" data-cid="n106" />
                      </div>
                    </div>
                    <div className="flex relative z-10 -mx-[0.6875rem] flex-wrap max-md:mx-[-3.3px] md:max-lg:mx-[-6.7px] 2xl:-mx-[0.825rem] after:content-[''] after:block after:w-0 after:h-0" data-cid="n107">
                      <div className="w-93.5 flex relative px-[0.7rem] items-stretch [background-position:50%_50%] max-md:w-[21.0375rem] max-lg:mb-[1.5625rem] max-md:px-[0.2125rem] max-lg:flex-wrap md:max-lg:w-[689.3px] md:max-lg:px-[6.9px] 2xl:w-[28.05rem] 2xl:px-[13.5px] after:content-[''] after:block after:w-0 after:h-0" data-cid="n108">
                        <div className="h-[49.6125rem] flex relative pr-5.5 flex-col justify-center grow max-md:h-[47.8125rem] max-md:pr-[11.3px] md:max-lg:h-[43.8125rem] md:max-lg:pr-4.5 2xl:h-[837.7px] 2xl:pr-[24.9px]" data-cid="n109">
                          <div className="h-[47.9375rem] min-h-px block max-md:h-[47.8125rem] md:max-lg:h-[43.8125rem] 2xl:h-[46.3125rem]" data-cid="n110">
                            <div className="block mb-6" data-cid="n111">
                              <div className="block" data-cid="n112">
                                <h3 className="block [font-family:'Cantata_One'] text-[1.6875rem] leading-8.5 max-lg:text-[1.625rem] max-lg:leading-[inherit] 2xl:text-[2rem] 2xl:leading-10" data-cid="n113" data-component="heading">
                                  Our Divisions
                                </h3>
                                {" "}
                              </div>
                              {" "}
                            </div>
                            {" "}
                            
                            <a className="h-12.5 inline-block relative mt-[1.5625rem] mb-12 py-[0.9375rem] px-[2.1875rem] rounded-[200px] text-background text-sm font-semibold leading-5 capitalize bg-primary cursor-pointer" data-cid="n132" data-component="button" href="/our-services" role="button">
                              <span className="inline-block relative whitespace-nowrap" data-cid="n133">
                                Learn more
                              </span>
                            </a>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                      <div className="w-187 flex relative px-[0.7rem] items-stretch [background-position:50%_50%] max-md:w-[21.0375rem] max-md:px-[0.2125rem] max-lg:flex-wrap md:max-lg:w-[689.3px] md:max-lg:px-[6.9px] 2xl:w-[56.1rem] 2xl:px-[13.5px] after:content-[''] after:block after:w-0 after:h-0" data-cid="n134">
                        <div className="flex relative flex-col justify-center grow" data-cid="n135">
                          <div className="min-h-px block" data-cid="n136">
                            <div className="flex flex-wrap gap-6" data-cid="n140">
                              <a className="group flex-1 min-w-55 block relative p-8.5 rounded-[10px] overflow-hidden text-background bg-primary" data-component="link" href="https://energy.hammerandanvil.co.za" target="_blank" rel="noopener noreferrer">
                                <h4 className="block [font-family:'Cantata_One'] text-[1.5rem] max-md:text-[1.375rem]" data-component="heading">
                                  Energy Solutions
                                </h4>
                              </a>
                              <a className="group flex-1 min-w-55 block relative p-8.5 rounded-[10px] overflow-hidden text-background bg-color-012" data-component="link" href="/our-services">
                                <h4 className="block [font-family:'Cantata_One'] text-[1.5rem] max-md:text-[1.375rem]" data-component="heading">
                                  Real Estate
                                </h4>
                              </a>
                              <a className="group flex-1 min-w-55 block relative p-8.5 rounded-[10px] overflow-hidden text-background bg-primary" data-component="link" href="/our-services">
                                <h4 className="block [font-family:'Cantata_One'] text-[1.5rem] max-md:text-[1.375rem]" data-component="heading">
                                  Mining
                                </h4>
                              </a>
                              <a className="group flex-1 min-w-55 block relative p-8.5 rounded-[10px] overflow-hidden text-background bg-color-012" data-component="link" href="/our-services">
                                <h4 className="block [font-family:'Cantata_One'] text-[1.5rem] max-md:text-[1.375rem]" data-component="heading">
                                  IT & Software Development
                                </h4>
                              </a>
                            </div>
                          </div>
                        </div>
                      </div>
                      {" "}
                    </div>
                  </div>
                  {" "}
                  <div className="box-content block relative pt-[4.8rem] pb-[3.2rem] bg-cover max-md:pt-[2.0625rem] max-md:pb-[0.9375rem] md:max-lg:pt-[4.225rem] md:max-lg:pb-[30.7px] 2xl:pt-[7.2rem] 2xl:pb-[4.8rem] before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n204" id="fws_6a84467767102">
                    <div className="h-full block absolute top-0 left-1/2 w-screen -translate-x-1/2" data-cid="n205">
                      <div className="h-full block absolute top-0 inset-x-0 z-1 overflow-hidden" data-cid="n206">
                        <div className="h-full block absolute top-0 inset-x-0 bg-primary bg-cover bg-no-repeat" style={{ backgroundImage: "url(\"/assets/cloned/images/616e4cecc6f0.jpg\")" }} data-cid="n207" />
                      </div>
                      <div className="h-full block absolute top-0 inset-x-0 z-3 opacity-95" style={{ backgroundImage: "linear-gradient(var(--color-012) 0%, var(--primary) 100%)" }} data-cid="n208" />
                    </div>
                    <div className="flex relative z-10 -mx-[0.6875rem] flex-wrap text-background max-md:mx-[-3.3px] md:max-lg:mx-[-6.7px] 2xl:-mx-[0.825rem] after:content-[''] after:block after:w-0 after:h-0" data-cid="n209">
                      <div className="flex relative px-[0.7rem] items-stretch [background-position:50%_50%] max-md:px-[0.2125rem] max-lg:flex-wrap md:max-lg:px-[6.9px] 2xl:px-[13.5px] after:content-[''] after:block after:w-0 after:h-0" data-cid="n210">
                        <div className="h-175.5 flex relative py-5.5 flex-col justify-center grow max-md:h-[1390.5px] max-md:py-[11.3px] md:max-lg:h-[50.5625rem] md:max-lg:py-4.5 2xl:h-[38.8625rem] 2xl:py-[24.9px]" data-cid="n211">
                          <div className="h-full min-h-px block" data-cid="n212">
                            <div className="block mb-6" data-cid="n213">
                              <div className="h-full block" data-cid="n214">
                                <h3 className="h-full block [font-family:'Cantata_One'] text-[1.6875rem] leading-8.5 text-center max-lg:text-[1.625rem] max-lg:leading-[inherit] 2xl:text-[2rem] 2xl:leading-10" data-cid="n215" data-component="heading">
                                  Why Choose Us?
                                </h3>
                                {" "}
                              </div>
                              {" "}
                            </div>
                            {" "}
                            <div className="block" data-cid="n216">
                              <div className="w-16 h-0.5 block my-16 mx-auto bg-background max-lg:my-10" data-cid="n217" />
                            </div>
                            <div className="block relative mb-6 pb-10 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n218" id="fws_6a844677679e5">
                              <div className="h-full block absolute top-0 inset-x-0" data-cid="n219">
                                <div className="h-full block absolute top-0 inset-x-0 bg-cover" data-cid="n220" />
                                {" "}
                              </div>
                              <div className="flex relative z-10 -mx-[0.6875rem] flex-wrap max-md:mx-[-3.3px] md:max-lg:mx-[-6.7px] 2xl:-mx-[0.825rem] after:content-[''] after:block after:w-0 after:h-0" data-cid="n221">
                                {FeatureCard2_data.map((d, i) => <FeatureCard2 key={i} d={d} cids={FeatureCard2_cids[i]} styles={FeatureCard2_styles[i]} />)}
                                {" "}
                              </div>
                            </div>
                            <div className="block relative pb-10 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n250" id="fws_6a844677691f4">
                              <div className="h-full block absolute top-0 inset-x-0" data-cid="n251">
                                <div className="h-full block absolute top-0 inset-x-0 bg-cover" data-cid="n252" />
                                {" "}
                              </div>
                              <div className="flex relative z-10 -mx-[0.6875rem] flex-wrap max-md:mx-[-3.3px] md:max-lg:mx-[-6.7px] 2xl:-mx-[0.825rem] after:content-[''] after:block after:w-0 after:h-0" data-cid="n253">
                                {FeatureCard3_data.map((d, i) => <FeatureCard3 key={i} d={d} cids={FeatureCard3_cids[i]} styles={FeatureCard3_styles[i]} />)}
                                {" "}
                              </div>
                            </div>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                  </div>
                  {" "}
                  <div className="box-content block relative py-[4.8rem] bg-cover max-md:pt-[2.0625rem] max-md:pb-[22.5px] md:max-lg:pt-[4.225rem] md:max-lg:pb-[2.875rem] 2xl:py-[7.2rem] before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n282" id="fws_6a8446776aa6e">
                    <div className="h-full block absolute top-0 left-1/2 w-screen -translate-x-1/2" data-cid="n283">
                      <div className="h-full block absolute top-0 inset-x-0 z-1 overflow-hidden" data-cid="n284">
                        <div className="h-full block absolute top-0 inset-x-0 bg-primary bg-cover" data-cid="n285" />
                      </div>
                      <div className="h-full block absolute top-0 inset-x-0 z-3 bg-primary" data-cid="n286" />
                    </div>
                    <div className="flex relative z-10 -mx-[0.6875rem] flex-wrap text-background max-md:mx-[-3.3px] md:max-lg:mx-[-6.7px] 2xl:-mx-[0.825rem] after:content-[''] after:block after:w-0 after:h-0" data-cid="n287">
                      <div className="flex relative px-[0.7rem] items-stretch [background-position:50%_50%] max-md:px-[0.2125rem] max-lg:flex-wrap md:max-lg:px-[6.9px] 2xl:px-[13.5px] after:content-[''] after:block after:w-0 after:h-0" data-cid="n288">
                        <div className="flex relative pr-[2.0625rem] flex-col grow max-md:pr-[11.3px] md:max-lg:pr-4.5 2xl:pr-[2.3375rem]" data-cid="n289">
                          <div className="h-full min-h-full block" data-cid="n290">
                            <div className="block relative mb-6 pb-4 before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n291" id="fws_6a8446776af7b">
                              <div className="h-full block absolute top-0 inset-x-0" data-cid="n292">
                                <div className="h-full block absolute top-0 inset-x-0 bg-cover" data-cid="n293" />
                                {" "}
                              </div>
                              <div className="flex relative z-10 mx-[-10.7px] flex-wrap max-md:-mx-[0.2rem] md:max-lg:-mx-[0.4125rem] 2xl:-mx-[0.8rem] after:content-[''] after:block after:w-0 after:h-0" data-cid="n294">
                                <div className="w-full block relative px-[10.9px] [background-position:50%_50%] max-md:px-[0.2rem] md:max-lg:px-[6.7px] 2xl:px-[0.8125rem] after:content-[''] after:block after:w-full after:h-0" data-cid="n295">
                                  <div className="block relative" data-cid="n296">
                                    <div className="block" data-cid="n297">
                                      <div className="block mb-6" data-cid="n298">
                                        <div className="block" data-cid="n299">
                                          <h3 className="block [font-family:'Cantata_One'] text-[1.6875rem] leading-8.5 text-center max-lg:text-[1.625rem] max-lg:leading-[inherit] 2xl:text-[2rem] 2xl:leading-10" data-cid="n300" data-component="heading">
                                            Our Process
                                          </h3>
                                          {" "}
                                        </div>
                                        {" "}
                                      </div>
                                      {" "}
                                      <div className="block" data-cid="n301">
                                        <div className="w-16 h-0.5 block my-16 mx-auto bg-background max-lg:my-3" data-cid="n302" />
                                      </div>
                                      {" "}
                                    </div>
                                    {" "}
                                  </div>
                                  {" "}
                                </div>
                                {" "}
                              </div>
                            </div>
                            <div className="block relative before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n303" id="fws_6a8446776b635">
                              <div className="h-full block absolute top-0 inset-x-0" data-cid="n304">
                                <div className="h-full block absolute top-0 inset-x-0 bg-cover" data-cid="n305" />
                                {" "}
                              </div>
                              <div className="flex relative z-10 mx-[-10.7px] flex-wrap max-md:-mx-[0.2rem] md:max-lg:-mx-[0.4125rem] 2xl:-mx-[0.8rem] after:content-[''] after:block after:w-0 after:h-0" data-cid="n306">
                                {FeatureCard4_data.map((d, i) => <FeatureCard4 key={i} d={d} cids={FeatureCard4_cids[i]} styles={FeatureCard4_styles[i]} />)}
                                {" "}
                              </div>
                            </div>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                  </div>
                  {" "}
                  
                  {" "}
                  <div className="block relative before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n469" id="contact">
                    <div className="h-full block absolute top-0 inset-x-0" data-cid="n470">
                      <div className="h-full block absolute top-0 inset-x-0 z-1 overflow-hidden" data-cid="n471">
                        <div className="h-full block absolute top-0 inset-x-0 bg-cover" data-cid="n472" />
                      </div>
                    </div>
                    <div className="flex relative z-10 -mx-[0.6875rem] flex-wrap max-md:mx-[-3.3px] md:max-lg:mx-[-6.7px] 2xl:-mx-[0.825rem] after:content-[''] after:block after:w-0 after:h-0" data-cid="n473">
                      <div className="w-full block relative px-[0.7rem] [background-position:50%_50%] max-md:px-[0.2125rem] md:max-lg:px-[6.9px] 2xl:px-[13.5px] after:content-[''] after:block after:w-full after:h-0" data-cid="n474">
                        <div className="h-full block relative" data-cid="n475">
                          <div className="h-full block" data-cid="n476">
                            <div className="box-content block relative z-100 py-[3.2rem] bg-cover max-md:py-[0.4125rem] md:max-lg:py-[13.5px] 2xl:py-[4.8rem] before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n477" id="fws_6a84467773273">
                              <div className="h-full block absolute top-0 left-1/2 w-screen -translate-x-1/2 overflow-hidden" data-cid="n478">
                                <div className="h-full block absolute top-0 inset-x-0 z-1 overflow-hidden" data-cid="n479">
                                  <div className="h-full block absolute top-0 inset-x-0 bg-cover" data-cid="n480" />
                                </div>
                              </div>
                              <div className="flex relative z-10 -mx-[0.6875rem] flex-wrap max-md:mx-[-3.3px] md:max-lg:mx-[-6.7px] 2xl:-mx-[0.825rem] after:content-[''] after:block after:w-0 after:h-0" data-cid="n481">
                                <div className="w-[11.6875rem] block relative px-[0.7rem] [background-position:50%_50%] max-md:w-[10.5125rem] max-lg:mb-[1.5625rem] max-md:px-[0.2125rem] md:max-lg:w-[13.4375rem] md:max-lg:px-[6.9px] 2xl:w-[224.3px] 2xl:px-[13.5px] after:content-[''] after:block after:w-full after:h-0" data-cid="n482">
                                  <div className="block relative" data-cid="n483">
                                    <div className="block" data-cid="n484" />
                                    {" "}
                                  </div>
                                  {" "}
                                </div>
                                {" "}
                                <div className="w-[747.7px] block relative px-[0.7rem] [background-position:50%_50%] max-md:w-[336.5px] max-lg:mb-[1.5625rem] max-md:px-[0.2125rem] md:max-lg:w-[43.0625rem] md:max-lg:px-[6.9px] 2xl:w-[56.075rem] 2xl:px-[13.5px] after:content-[''] after:block after:w-full after:h-0" data-cid="n485">
                                  <div className="h-full block relative" data-cid="n486">
                                    <div className="h-full block" data-cid="n487">
                                      <div className="block relative mb-6 pb-[3.175rem] max-md:pb-[1.4375rem] md:max-lg:pb-[47.3px] 2xl:pb-[3.8125rem] before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n488" id="fws_6a844677739d6">
                                        <div className="h-full block absolute top-0 inset-x-0 overflow-hidden" data-cid="n489">
                                          <div className="h-full block absolute top-0 inset-x-0 bg-cover" data-cid="n490" />
                                          {" "}
                                        </div>
                                        <div className="flex relative z-10 -mx-[0.45rem] flex-wrap max-md:mx-[-3.3px] md:max-lg:mx-[-6.7px] 2xl:mx-[-8.7px] after:content-[''] after:block after:w-0 after:h-0" data-cid="n491">
                                          <div className="w-full block relative px-[0.4625rem] text-center [background-position:50%_50%] max-md:px-[0.2125rem] md:max-lg:px-[6.9px] 2xl:px-[8.9px] after:content-[''] after:block after:w-full after:h-0" data-cid="n492">
                                            <div className="h-full block relative" data-cid="n493">
                                              <div className="h-full block" data-cid="n494">
                                                <div className="h-full block" data-cid="n495">
                                                  <div className="h-full block" data-cid="n496">
                                                    <h5 className="block mb-[0.4375rem] [font-family:'Cantata_One'] text-xl leading-7" data-cid="n497" data-component="heading">
                                                      Let’s Innovate
                                                    </h5>
                                                    {" "}
                                                    <h2 className="block [font-family:'Cantata_One'] text-[2.5625rem] leading-[3.0625rem] max-md:text-4xl max-md:leading-[2.75rem] md:max-lg:text-[2.375rem] md:max-lg:leading-[2.875rem] 2xl:text-5xl 2xl:leading-14.5" data-cid="n498" data-component="heading" data-ditto-animate="fade-up">
                                                      Message Us
                                                    </h2>
                                                    {" "}
                                                  </div>
                                                  {" "}
                                                </div>
                                                {" "}
                                              </div>
                                              {" "}
                                            </div>
                                            {" "}
                                          </div>
                                          {" "}
                                        </div>
                                      </div>
                                      <div className="block relative before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n499" id="fws_6a8446777402b">
                                        <div className="h-full block absolute top-0 inset-x-0 overflow-hidden" data-cid="n500">
                                          <div className="h-full block absolute top-0 inset-x-0 bg-cover" data-cid="n501" />
                                          {" "}
                                        </div>
                                        <div className="h-[32.5625rem] flex relative z-10 -mx-[0.45rem] flex-wrap max-md:h-[37.5625rem] max-md:mx-[-3.3px] md:max-lg:h-[33.7375rem] md:max-lg:mx-[-6.7px] 2xl:h-[30.8rem] 2xl:mx-[-8.7px] after:content-[''] after:block after:w-0 after:h-0" data-cid="n502">
                                          <div className="w-full block relative -mb-[11.5625rem] px-[0.4625rem] rounded-[10px] [background-position:50%_50%] max-md:-mb-[5.25rem] max-md:px-[0.2125rem] md:max-lg:-mb-[10.7625rem] md:max-lg:px-[6.9px] 2xl:-mb-[13.875rem] 2xl:px-[8.9px] after:content-[''] after:block after:w-full after:h-0" data-cid="n503">
                                            <div className="h-full block relative p-[2.0625rem] rounded-[10px] max-md:p-[22.5px] md:max-lg:p-9 2xl:p-[2.3375rem]" data-cid="n504">
                                              <div className="w-[45.3125rem] h-full block absolute top-0 left-0 -z-1 rounded-[10px] overflow-hidden shadow-[var(--clr-3)_0px_60px_135px_0px,var(--clr-3)_0px_15px_65px_0px] pointer-events-none max-md:w-[20.6rem] md:max-lg:w-[42.1875rem] 2xl:w-[54.375rem]" data-cid="n505">
                                                <div className="h-full block absolute top-0 inset-x-0 -z-1 bg-background pointer-events-none" data-cid="n506" />
                                              </div>
                                              {" "}
                                              <HomeContactForm />
                                              {" "}
                                            </div>
                                            {" "}
                                          </div>
                                          {" "}
                                        </div>
                                      </div>
                                      {" "}
                                    </div>
                                    {" "}
                                  </div>
                                  {" "}
                                </div>
                                {" "}
                                <div className="w-[11.6875rem] block relative px-[0.7rem] [background-position:50%_50%] max-md:w-[10.5125rem] max-md:px-[0.2125rem] md:max-lg:w-[13.4375rem] md:max-lg:px-[6.9px] 2xl:w-[224.3px] 2xl:px-[13.5px] after:content-[''] after:block after:w-full after:h-0" data-cid="n541">
                                  <div className="block relative" data-cid="n542">
                                    <div className="block" data-cid="n543" />
                                    {" "}
                                  </div>
                                  {" "}
                                </div>
                                {" "}
                              </div>
                            </div>
                            {" "}
                            <div className="box-content block relative bg-cover before:content-[''] before:table before:w-0 before:h-0 after:content-[''] after:table after:w-0 after:h-0" data-cid="n544" id="fws_6a84467775939">
                              <div className="h-full block absolute top-0 left-1/2 w-screen -translate-x-1/2" data-cid="n545">
                                <div className="h-full block absolute top-0 inset-x-0 z-1 overflow-hidden" data-cid="n546">
                                  <div className="h-full block absolute top-0 inset-x-0 bg-cover" data-cid="n547" />
                                </div>
                              </div>
                              <div className="flex relative z-10 -mx-[0.6875rem] flex-wrap max-md:mx-[-3.3px] md:max-lg:mx-[-6.7px] 2xl:-mx-[0.825rem] after:content-[''] after:block after:w-0 after:h-0" data-cid="n548">
                                <div className="w-full block relative px-[0.7rem] [background-position:50%_50%] max-md:px-[0.2125rem] md:max-lg:px-[6.9px] 2xl:px-[13.5px] after:content-[''] after:block after:w-full after:h-0" data-cid="n549">
                                  <div className="h-full block relative" data-cid="n550">
                                    <div className="h-full block" data-cid="n551">
                                      <div className="h-full block" data-cid="n552">
                                        <div className="h-full block" data-cid="n553" />
                                      </div>
                                      {" "}
                                    </div>
                                    {" "}
                                  </div>
                                  {" "}
                                </div>
                                {" "}
                              </div>
                            </div>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
            <div className="block relative z-10 text-muted-foreground bg-surface-3" data-cid="n554" id="footer-outer">
              <div className="block" data-cid="n555" id="footer-widgets">
                <div className="block relative max-w-375 px-22.5 max-lg:max-w-[88%] max-md:mx-[22.5px] max-lg:px-0 md:max-lg:mx-[2.875rem] 2xl:mx-52.5 before:content-['_'] before:table before:w-0 before:h-0 before:text-muted-foreground before:text-base before:leading-8 after:content-['_'] after:table after:w-0 after:h-0 after:text-muted-foreground after:text-base after:leading-8" data-cid="n556">
                  <div className="block relative py-[4.6875rem] max-lg:py-[3.4375rem] before:content-['_'] before:table before:w-0 before:h-0 before:text-muted-foreground before:text-base before:leading-8 after:content-['_'] after:table after:w-0 after:h-0 after:text-muted-foreground after:text-base after:leading-8" data-cid="n557">
                    <div className="w-[24.0625rem] h-16 min-h-px block relative float-left z-10 mr-5.5 max-md:w-82.5 max-lg:mb-10 max-md:mr-0 md:max-lg:w-[20.275rem] md:max-lg:h-31.5 md:max-lg:clear-both md:max-lg:mr-[0.9375rem] md:max-lg:p-[0.9375rem] 2xl:w-115.5 2xl:mr-[1.65rem] after:content-[''] after:block after:w-full after:h-0" data-cid="n558">
                      <div className="h-full block" data-cid="n559" id="text-1">
                        <div className="h-full block" data-cid="n560">
                          <p className="h-full block" data-cid="n561">
                            Copyright © 2025 Hammer and Anvil Ventures
                            <br className="inline" data-cid="n562" />
                            {" All rights reserved."}
                          </p>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <div className="w-[214.5px] h-62 min-h-px block relative float-left z-10 mr-5.5 max-md:w-82.5 max-md:h-[15.3rem] max-lg:mb-10 max-lg:mr-0 md:max-lg:w-[20.275rem] md:max-lg:h-69.5 md:max-lg:p-[0.9375rem] 2xl:w-[16.0875rem] 2xl:mr-[1.65rem] after:content-[''] after:block after:w-full after:h-0" data-cid="n563">
                      <div className="block" data-cid="n564" id="nav_menu-1">
                        <h4 className="block mb-5 text-color-004 [font-family:'Cantata_One'] capitalize max-md:leading-[1.8125rem]" data-cid="n565" data-component="heading">
                          Discover
                        </h4>
                        <div className="block" data-cid="n566">
                          <ul className="block [list-style-type:none] list-outside" data-cid="n567" id="menu-main-nav-2">
                            {ListRow3_data.map((d, i) => <ListRow3 key={i} d={d} cids={ListRow3_cids[i]} styles={ListRow3_styles[i]} />)}
                          </ul>
                        </div>
                      </div>
                      {" "}
                    </div>
                    {" "}
                    
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
          <a className="w-[1.8125rem] h-[1.8125rem] block fixed top-[48.1875rem] left-308.5 z-9994 min-w-0 rounded-[200px] overflow-hidden text-background leading-3 text-center bg-color-009 [background-position:50%_50%] bg-no-repeat transform-[matrix(1,0,0,1,0,30.45)] cursor-pointer before:content-['_'] before:block before:absolute before:inset-0 before:z-2 before:w-[1.8125rem] before:h-[1.8125rem] before:text-background before:text-base before:leading-3 before:text-center before:bg-clr-6 before:opacity-0 before: before:origin-[14.5px_14.5px] before:rounded-tl-[100px] after:content-['_'] after:block after:absolute after:inset-0 after:z-1 after:w-[1.8125rem] after:h-[1.8125rem] after:text-background after:text-base after:leading-3 after:text-center after:bg-primary after:transform-[matrix(0,0,0,0,0,0)] after:origin-[14.5px_14.5px] after:rounded-tl-[100px]" data-cid="n600" aria-label="Back to top" href="#" id="to-top">
            <i className="h-[1.8125rem] inline-block relative z-10 max-w-full align-middle [font-family:icomoon] text-sm leading-[1.8125rem] [word-spacing:1px] before:content-[''] before:text-background before:text-sm before:leading-[1.8125rem] before:text-center" data-cid="n601" role="presentation" />
            <i className="h-[1.8125rem] inline-block relative z-10 max-w-full align-middle [font-family:icomoon] text-sm leading-[1.8125rem] [word-spacing:1px] before:content-[''] before:text-background before:text-sm before:leading-[1.8125rem] before:text-center" data-cid="n602" role="presentation" />
          </a>
          {" "}
        </div>
      </div>
    </>
  );
}
